### ISSUE TITLE
Das Reich / Fall Wies game path corruption 

### ISSUE THREAD

**Issue by Cjh1953** [nicupavel/openpanzer#145]
When I finish a Das Reich game on line in the beta version the next game that sets up is Burza. Finish Burza and I go to a Das Reich game. Also, just caputured the only victory hex in Lila and no victory. The only way out is to lose. 

This means that a couple of work around solutions for the iPad app don’t work - Typhoon Called off and the transition between Hedgerows and Luttich. 

Is the beta corrupted?

**Comment by Lutarp** [comment]
I have had the exact same issue

**Comment by Lutarp** [comment]
I have the save file for bzura counterattack that contains the corrupted game path. Once again this game file was from before the update, so that may be the reason.

**Comment by Lutarp** [comment]
I had to rename it a text file to post, change it back to Json to use

**Comment by Lutarp** [comment]
[(Campaign) Bzura Counterattack Turn 8 Wed Oct 10 2018 5_45_08 PM.txt](https://github.com/nicupavel/openpanzer/files/2466622/Campaign.Bzura.Counterattack.Turn.8.Wed.Oct.10.2018.5_45_08.PM.txt)
![screenshot 16](https://user-images.githubusercontent.com/16502495/46768221-64f93280-ccb5-11e8-8e60-e27edf74b45f.png)

**Comment by Lutarp** [comment]
As you can see, the text bubble that appears is from victory in the Das reich campaign, and this leads to french army push north. Another issue after this is that victory is unobtainable on the following mission, and holding all objectives or reclaiming them or even exterminating every french unit does not start the victory conditions. Following this the game continues on the das reich game path as per normal, but I am not sure if the victory issue persists. This sudden change is fine, I just wanted to know that when entering the french army push north mission if you had comparable amounts and quality of units as when you arrived at this mission via the normal das reich campaign path

**Comment by Lutarp** [comment]
@nicupavel

**Comment by salexgit** [comment]
Hi Lutarp

Thanks for uloading the saved game. I tested the game and indeed the game engine jumps to the scenario from a different campaign. This problem does not occur with 2.9.7, i.e. the same saved game moves correctly to the next scenario in the Polish campaign.

I thought that the problem is due to corrupted campaign description file, but I checked 018.json and 023.json file, and they are absolutely fine.

@nicupavel It seems that you introduced some changes in the scenario transition code, and whatever those changes are, they cause weird behaviour even though .json campaign files are correct.

**Comment by nicupavel** [comment]
I'll look thanks for pointing this up.
BTW it's easy to save to cloud and send me/post here the ID of the save.

**Comment by nicupavel** [comment]
The issue is that latest update changed the order of campaigns and older saves will be broken:

```
  "campaign": {
    "id": "0",
    "scenario": 1,
    "country": 7,
```
id should be 1 now. This is something that slipped my mind atm not sure if we should put order back or continue like this.

**Comment by salexgit** [comment]
Hi all

@Lutarp Can you please start a new campaign with 2.9.8 and confirm that the bug is still there?  According to Nicu's explanations, the bug could be caused by the fact that the game was saved with 2.9.7 and opened in 2.9.8.

@Nicu I realized now that the saved game format points to the campaign as an index, not as a particular .json file name, which means that whenever we add/remove campaigns, the same problem might occur again. It is of course not something that we can address in 2.x, but I would suggest considering to refer to campaign as an explicit ID/name, not an index.

**Comment by Cjh1953** [comment]
Hi Nicu: I play this on my iPad and use the on-line version to get around the issues with the transition from Hedgerows to Luttich (Called off and March to Limoges as well).  

 

I am in the midst of a campaign and the file path loop problem has made it a very strange one, jumping back and forth from Weiss to Das Reich. I am now stuck at Hedgerows. 

 

If I save to the cloud and occupy all the victory hexes it will not move on to Luttich. If I save to the cloud, open it on-line and occupy those hexes I go to Burza. 

 

I am not a software expert like yourself and the others.

 

I am hoping somehow to finish this campaign however even if I abandon it, I cannot start a new one as the same issue will occur given the issue bridging from 2.9.0 to 2.9.8. 

 

Any help would be greatly appreciated. I really like this game. It is far and away the best WW2 game on iPad. 

 

Thanks

 

Chris

647.885.2292

**Comment by nicupavel** [comment]
I'm planning to update the iOS version next week along with a new Android version that fixes some of the issues.

**Comment by Cjh1953** [comment]
Fantastic! Thank you.

 

Chris

647.885.2292

**Comment by Lutarp** [comment]
Is there anyway to directly edit the save data index of a dowload save by
using control f in word?

**Comment by salexgit** [comment]
The saved game is in the JSON format, so you can edit it easily in any editor you want, assuming of course you know what you do :)
