### ISSUE TITLE
Aufklara 

### ISSUE THREAD

**Issue by LaughtersGrave** [nicupavel/openpanzer#158]
Aufklara need to be upgraded to have radfahrer to become all terrain?

They're already on bikes, it doesn't make sense.

I propose that Aufklara become all terrain by default and remove the option to have radfahrer. 

Like how you mount an infantryman, on a bike and mount that bike on a bike? Doesn't make sense.

**Comment by salexgit** [comment]
Hi

I can check it further, but if Radfahrer are all terrain, then it is wrong. I suppose they should be wheeled. I also noticed that Aufklara has different transport options, which is strange/wrong.

**Comment by LaughtersGrave** [comment]
Agree.

If Aufklara are going to be worth anything they need to be all terrain or legged for mechanics purposes otherwise you've got no reason the but these over Kavallrie.

**Comment by salexgit** [comment]
Hi again

I did not inspect Kavalerie vs. Aufklara balance, but it should be somewhat similar to half-tracked vs. full-tracked. In other words, an all terrain unit has benefits in e.g. swaps and mountains, but it is not as fast as a wheeled unit on roads.

**Comment by LaughtersGrave** [comment]
Agree but right now some Kavallrie is half tracked movement, some is leg, some is mountain leg and some is all terrain.

Krad Scutze and Aufklara, while legitimately wheeled, should, for in game mechanics and representation of rule and real life function, be classed as half tracked. Because they should be able to perform on mountains and hills, they were designed for that purpose.

**Comment by LaughtersGrave** [comment]
I just noticed that the gebirgsaufklarung bike unit has an unusually small movement of 4 when all other bike units have 6 or 8. Given its nature of being a reconnaissance unit it could really do with having 8 movement.

**Comment by LaughtersGrave** [comment]
I mean seriously, look at the fj Aufklarungs they literally WALK at the same speed an agile gebirgsaufklarung motor bike unit moves, that's plain bs. The bike needs it's movement doubled to 8

**Comment by salexgit** [comment]
Hi

Just for information, I am introducing some fixes into the equipment file, so I will take a closer look at this issue.

**Comment by salexgit** [comment]
Hi again

I checked further unit information, and to be honest I failed to get what your concern is. Here is my summary of unit characteristics:
- Bike and motorbike infantry are modeled as wheeled one, makes sense as for me.
- Cavalry is modeled as half-tracked, also make sense as a cavalry can explore more challenging terrains.
- Bike infantry and cavalry has the same moving range of 5, while motorbike infantry has range of 8. Ok, one could argue that cavalry moving range should be around 6-7, especially accounting for the fact that recon cavalry has moving range of 6.
- Speaking of recon units, there are indeed all terrain versions of bike infantry and cavalry. However, they are either more expensive or less powerful when compared to "wheeled" versions. I nevertheless could agree to the point that (maybe) recon bike infantry should be modeled as half-tracked.
- The only discrepancy that I noticed is that in some cases cavalry units have transport options, I assume it should be removed. Maybe the same principle should be applied also to the bike infantry because in principle you can load infantry with bikes on a truck :) 

Regards, Alex

**Comment by LaughtersGrave** [comment]
So you don't get what the problem with a motorbike unit only being able to move 4 hexes?

Ok

**Comment by LaughtersGrave** [comment]
Aufklara are wheeled... Yes, it's true, but unlike other wheeled units armoured cars, trucks, cars, etc they are designed to deal with rough terrain and they're already much weaker than contemporary infantry. As it is you're never going to buy them because they're useless, you get a lot more movement from regular infantry in halftracks, or cars and they're much more powerful than aufklara. And since infantry can never be attacked in their transports (as they jump out instantly) then why would you ever buy Aufklara?

**Comment by barsoom1717** [comment]
Alex, can the equipment file be posted or linked to?

**Comment by salexgit** [comment]
Hi LaughtersGrave

Ok, now I am getting a bit better what your question is. So, I checked "gebirgsaufklarung" units and all of them have moving range of 4. Please note that this is not only about bike infantry "gebirgsaufklarung", but also cavalry "gebirgsaufklarung". I suspect that this was done intentionally to counter-balance a bit the fact that these units have the mountain moving bonus; normal bike infantry and cavalry still have moving range of 5. Sooo.... nobody forces you to buy "gebirgsaufklarung" units because they would be useful only if you play a mountain campaign :) 

Regarding reasons to buy (moto-)bike infantry, they are cheaper than infantry with e.g. OpelBlitz transport, but less powerful. Furthermore, they can move at range 5 and still attack, whereas a normal infantry has to be loaded on a transport and will be able to attack only at the next turn. So, as for me trade-offs are rather obvious.

**Comment by LaughtersGrave** [comment]
Ok I'll stick to movement 7 panzer grenadiers which don't suck and can actually move further in a mountain than gebirgsaufklarung lol.

Tbh there's a point where game "balance" just makes the attempt to call it realistic hilarious.

**Comment by salexgit** [comment]
Hi

I am not the one who designed the first version of the equipment file so I can only express my respect to people who did that tremendeous amount of work abstaining from calling their attempts to maintain game balance as "hillarious". There are obvious bug and inconsistencies which we usually fix immediately, and there are less straightforward cases. Anyway, we do not close this issue - I just wanted to clarify that I got it right :)
