### ISSUE TITLE
Smolensk - Crossing the Dnepr: Units vanish and appear mirrored on other side of map

### ISSUE THREAD

**Issue by fallen262** [nicupavel/openpanzer#164]
After setting up my units on the Smolensk - Crossing the Dnepr map, when moving sonme units suddenly most of the german units disappear from theie position and are shown on the right side of the map like "mirrored". When saving and reloading all seems ok at first until the same happens again after the first movement. Computer turn is not being processed to the end after choosing to end the turn. I can see units popping up and disappearing while the computer is "playing".

**Comment by salexgit** [comment]
Hi

Can you please check issue #118 and confirm whether you have the same problem?

**Comment by fallen262** [comment]
Yes, that´s exactly the same problem. Playing on Win 10 with firefox. Tried for 2 days, no change.

**Comment by salexgit** [comment]
Hi

Can you try a different browser? Last time the problem was reported with Chrome but it was circumvented around by using Firefox.
 
If possible, can you also upload here the saved game so that we can (try to) reproduce the problem? It may be a weird coincidence, but so far the problem occurs only with "Smolensk - Crossing the Dnepr" scenario.
