### ISSUE TITLE
Equipment List?

### ISSUE THREAD

**Issue by barsoom1717** [nicupavel/openpanzer#169]
Are there any equipment lists available?  Would like to know the "epid" of the different units.

**Comment by LaughtersGrave** [comment]
I've just posted that request myself. But basically until Russia you should be wanting/getting FW190 A-3

**Comment by salexgit** [comment]
Hi

Yes, I also agree that it would be nice to have the such a list so that you can browse easily through units and their capabilities. As for me this should be also complemented by additional unit attributes which are not shown on the moment. For instance some infantry units ignore entrenchment bonus, but it is not shown anywhere. Some anti-air units, such as flaks, can also attack ground units, but it is not indicated either, etc.
