### ISSUE TITLE
Cost of upgrading

### ISSUE THREAD

**Issue by LaughtersGrave** [nicupavel/openpanzer#172]
I've noticed that some units cost more to upgrade than buying a whole new unit if the same type, but some things are much cheaper.

For example

Upgrading my FW190 A-3 to He219 costs 300ish
But to upgrade my 10.5 LeFH 18 to 21 K38 costs nearly 1800 which is insane

**Comment by salexgit** [comment]
Hi

The way it basically works is that the unit price difference (including transports) is multiplied by upgrade penalty, which is 1.25. So, 10.5 leFH is pretty cheap, just 228, and 21 K38 is quite expensive. The price difference is then multiplied by 1.25 yielding quite high a price. 
I am not challenging current model but I agree that in some cases upgrading a very cheap unit to a very expensive unit may result in a higher price than just buying a new expensive unit :)

**Comment by LaughtersGrave** [comment]
Ouch.

OK thanks. 

It does seem weird

**Comment by nicupavel** [comment]
... and factor in the current unit experience, which will transfer to the new unit.

**Comment by salexgit** [comment]
Hi all

So, here are my preliminary considerations on how it might work

- We can assume that if the source unit price is "A", and the target unit price is "B", then upgrade cost should not exceed "B", i.e. it should not be more than just buying a new unit for price B.
- In other words, what matters is refund you get for selling the source unit, i.e. KA, where K=[0..1] controls how much refund you get.
- The easiest way would be just to set K to some fixed value, e.g. 0.75, so that you always get some constant refund. 
- A more interesting approach is to calculate K based on the source and target unit prices; for instance K=A/B. The rationale behind is that you get a higher refund when the price difference is small, which can be viewed as a minor upgrade in the real life. Once price difference becomes larger, the refund becomes smaller.

Just my thoughts on how it can be implemented. I am not sure whether we need to account for anything else, such as experience, because both experience and leader attributes will be anyway copied to a new unit.

**Comment by LaughtersGrave** [comment]
That sounds like a good formula to me, I assume transport cost is also factored in, so if you're not selling the transport, you're keeping the same one, no refund, but cheaper price upgrade (fractionally) because you don't need to upgrade your transport.... But, if you do upgrade the transport too then that should be additionally deducted from the overall upgrade cost

**Comment by LaughtersGrave** [comment]
So I took a screen shot... Are you sure you have the formular correct? 
He219 1104 
Fw190A-3 1008
The difference is 96 x 1.25 = 120 yet, as you can see in the screen shot the price is 372

![screenshot_2018-11-18-00-26-24-975_com ecosia android](https://user-images.githubusercontent.com/44041995/48667185-c092b900-eac8-11e8-805d-94a6ae192aaf.png)

**Comment by salexgit** [comment]
Hi

I did not analyze all the code details - so it could be the case that something else is taken into account.
