### ISSUE TITLE
app issues

### ISSUE THREAD

**Issue by juniorjuniorjj** [nicupavel/openpanzer#173]
Hi all,

Just have to say that I found this game after panzer corps came out and since discovering it, I find it way more enjoyable than PC or any other ww2 strategy to date - there are a few issues though that are a bit frustrating and was wondering if there were plans for updates to the app - 

DR Campaign:

1. Fallshirm units have no airborne deployment capability, only in the student scenario are they able to be used as true airborne, and only non-core units have that capability. *key issue as in later scenarios there are victory hexes that have no access via land units- 

2. Limoges - can deploy units but they are blocked by a wall that shows up on the terrain map, I just had to let france win the victory hexes and lose the scenario to advance the campaign. is there something I'm missing? 

3. hidden objectives in 4th battle of kharkov, found the answers in another thread, also brilliant victory in only 1 turn on this? how is that possible? 

4. Hedgerows: after brilliant victory in hedgerows the game crashes and claims a resolution error, only fix is to delete the app entirely and reload, all saved games on disk are lost. this happened a couple of times to me - would like to finish the campaign at some point, to date this is as far as I have gotten. Have not tested this with a newer ipad, mine is definately due for an upgrade.

5. Vyazma: core units have no deployment hexes. just like limoges, I just had lose the scenario to advance the campaign. 

6. Upgrades: some of the unit upgrade models are a bit counter intuitive. in some cases it costs more to downgrade a unit - 

7. air units: the air recon units only have a visibility of 2 hexes, i believe the me110 is the only unit with a visibility of 3 hexes, is that right? 

8. the 88 - essentially a useless unit in this campaign, a couple of times it helped defend my arty but for such a prominent item in the theatre, i found it to be just another slow unit behind the lines

9. Typhoon called off: hidden victory hex on mountain on west side of map - impossible to complete - could do it if the fallshirm actually worked, see issue 1

I think thats it, figuring out the interface took some time, the tutorial isnt very informative, i remember even just figuring out to  end a turn was frustrating. 

I think student is the only scenario where I was unable to get brilliant victory that actually is a completely functioning scenario. limoges,typhoon and vyazama are clearly bugged.

**Comment by salexgit** [comment]
Hi

Can you indicate which version do you play? Some of the issues, which you mentioned, should have been fixed and are under testing. Please visit http://openpanzer.net/beta

Anyway, here are my comments on comments:

1. I agree. This has been discussed quite extensively in #152, so I hope that the whole concept of air-borne units will become more interesting in next releases.

2. This must have been fixed, I will double check.

3. The hidden objective must have been fixed. Regarding the brilliant objective in 1 turn, this is how we usually model "defensive" scenarios.

5. I will double check as this issue must have been fixed.

6. See discussion thread #172.

7. I agree. You might be interested to read discussion #117.

8. I assume you complain about slow Flak unit? This is going to be fixed (I hope).

9. This should have been fixed.

Regards, Alex

**Comment by LaughtersGrave** [comment]
I hope we soon have flak units functioning as flak units, because you have to tow them like artillery, but then they can't jump out like infantry, which means they are utterly useless unless they can attack... Which they can't currently.

My advice is upgrade your 2cm flak to an sdkfz 7/1 it's the only other unit that can attack until 1945. When you get the flakpanzer 38(t) which is actually way worse, and you can no longer buy the 7/1. The only other air defense unit that can attack ground units is the flakvierling 38 which is actually OK vs ground targets. But you can't normally buy them and you can never upgrade your units into them (until they change flak units). The way to buy them, (and I wouldn't tbh, I'd rather spend prestige on fighters) is when you are on operation Typhoon Borodino you will see your first flakvierling as an auxiliary unit, you just click it and go to the purchase menu, with the flakvierling highlighted the button to purchase will show up and you can then spend prestige to get one. 

Either way, don't waste your prestige on the big AA units, none of them are worth the money. 

I would also council against buying any fj infantry and any fj light artillery, since there are no airports with transports on Das Reich campaign (except one on student that is only accessible by an auxiliary unit since you'd spend longer getting there to use with core units than you'd save in time by using it) they're utterly useless. I would be so bold as to say use only the standard ss infantry you start with and sturmpioners until 1943 when you can get 43 ss panzer grenadiers which are superior infantry.

You are correct about the me110D I would not bother with them as they are expensive for a not very good unit. Stick with your first recon and then a few additional 233 (they're good at mashing infantry which are found on mass, so good source of experience) until 44 when you can get 234/4 which have a 2 hex range which is invaluable in doing damage, getting experience and suffering no damage.

I don't want to badger you but I'd council you to get only He111 as bombers all the way through to 45 I bought 8 by 40 and didn't bother buying any more till 45 in 42 you have only two missions are the rewards for brilliant victory and not so substantial as they were when you could get FW190A in 39 and 40, in 41 I took 1 tiger then bought more and took lots of the 21 K38 artillery (the best, buy all you need before 45, they disappear) in 42 the best you can get is the FW190G bomber in 43 you can get tiger 2 which is the best of the options imo or the jet bomber (which is really not much of an improvement over your very much cheaper He111) or the early and not so good Me262 jet fighter (it's not the good later version).

Anyways that's my (probably unwanted) opinion, I hope it helps.
