### ISSUE TITLE
4th Battle of Kharkov - 1 turn for BV?

### ISSUE THREAD

**Issue by barsoom1717** [nicupavel/openpanzer#177]
Just wondering if I am seeing a glitch.  You have to get the two victory objectives (at opposite sides of the map) on the first turn?  So, if its not a glitch, I guess its impossible to get a BV on this one?  With the two deployment hexes in the middle of the map, my fastest unit can't even drive to either of the objectives in one turn, much less dealing with any opposition..

**Comment by barsoom1717** [comment]
Has anyone gotten a BV in this scenario?  Does it affect the game path any to only get a Victory instead of a BV?

**Comment by salexgit** [comment]
Hi

I am not the one who designed the scenario, but I noticed that sometimes 1 turn for BV is used to model so-called "defensive" scenario. PanzerGeneral did not have a concept of the defensive game, so it is modelled as e.g. 1 turn for BV and X turns for V/TV. I saw similar a trick in other scenarios. In some cases the "defensive" scenario is designed in such a way that you cannot win it at all: the point is that you need to defend your tiles for X turns, after which you "lose", but the campaign continues.

Referring to historical records, the 4 th Battle for Kharkov was a huge meat-grinder comprising Soviet offensive, Germany counter-attack, followed by the Soviet 5th Guard Tank army counter-offensive, which forced Germans to turn into the defensive mode. They almost got ambushed in Kharkov and finally had to leave it to establish a new defensive line at Dnepr. 

My recommendation is not to do any changes now in the scenario. I had an idea of changing it a bit to make it closer to historical events; in fact it could be part of more radical changes to the DasReich campaign because some scenarios are not very accurate either. Furthermore, some big DasReich battles are even missing, such as Zhitomyr and Korsun.

**Comment by barsoom1717** [comment]
Just offering my opinion, but I don't think it is necessarily a good thing to be locked into historical accuracy.  In fact, that is one reason I loved the old PG so much, i.e. if you were good enough you could change history.  If I'm going to be forced by the game in every scenario to repeat history, I don't think I will (speaking for myself) have much interest in playing.

**Comment by salexgit** [comment]
Hi barsoom

If you take a look at campaigns' descriptions designed for PG and its clones such as OpenPanzer, then you will see that most of them mention explicitly whether it is a historical one or not. DasReich and LSSAH are historical campaings designed by people who love history for gamers who are picky about historical details trying to capture even unit names that took part in particular battles. If you want to have just fun, fair enough, then just pick one of the semi-historical campaigns that are not linked to any particular division or army group. However, having fun should be not used as an argument to ruin historical accuracy of certain campaigns, for which people spent hunders of hours and whose work I personally respect a lot.

Regards, Alex

**Comment by barsoom1717** [comment]
All good points Alex.  I understand there will be people who want extremely historically accurate games.  I was a history major in college, so although I understand there are many who want it, for me however, if I want extreme historical accuracy, I just read the books on the subject.  But I respect there are people who want that.

I didn’t realize there was a distinction between the campaigns.  Could you suggest one of the semi-historical campaigns?  The longer and more encompassing the better.

Thanks.

Stephen

**Comment by salexgit** [comment]
Hi Stephen

As an example, if you visit the following website, you will see a number of different campaigns. 
http://www.adlerkorps.com/

Some of them are more or less accurate historical ones, while some of them are semi-historical in a sense that they do not follow any particular unit/division. Some of them are purely fictional, such as Red World Order :)

OpenPanzer is just an engine that is capable of processing those campaign files and we usually take them as they are. Sometimes we of course introduce minor fixes and corrections :)

**Comment by barsoom1717** [comment]
Are there any instructions anywhere on how to load those campaigns into OpenPanzer?  There are several there I would like to try.

Stephen

**Comment by barsoom1717** [comment]
Thanks so much Alex, I really appreciate it.  Yes, that would be great.  Looking at the campaigns available; any one of these would be awesome:  German World campaign (original), Greater Europe, or Blitz 2008.

Stephen

**Comment by salexgit** [comment]
Hi Stephen

Ok, I will do my best to convert those campaigns asap. I cannot promise that they will immediately become available as e.g. online beta because it is not controlled by me. However, I can try to prepare an offline package with those campaigns included so that you can try them locally on a desktop computer.

Regards, Alex

**Comment by LaughtersGrave** [comment]
I'm doing this now and I can confirm it is IMPOSSIBLE to get a first turn victory.

This is definitely a bug that needs to be fixed. 

It's impossible to do this map in under 6 turns as there's no air transports and there's a river you have to cross in two places, plus get behind the impassible escarpment which has a major objective where the is insanely well entrenched (I think it was 30 or more)

**Comment by barsoom1717** [comment]
Hi Alex, have you had any luck with converting the new campaigns?  I've seen a few posts that sounded like you were trying but were running into issues, but wasn't sure.

Stephen

**Comment by salexgit** [comment]
Hi Stephen

One campaign - Wacht am Rhein - is ready; I did not test it thoroughly but at least I did not find any critical issues. Another campaign - 1st SS panzer division "LSSAH", which is conceptually similar to existing 2nd SS panzer division "Das Reich" - has some issues with one particular scenario. I hope it will be resolved soon.
Current plan is to add those campaigns to online beta (together with other fixes). I will post a message once they become available.

Regards, Alex

**Comment by barsoom1717** [comment]
Thanks so much Alex.   All your hard work is greatly appreciated.

 

Stephen

**Comment by barsoom1717** [comment]
Thanks Alex!  When you say offline, that means I’ll only be able to play them on my computer, not my Android tablet?

**Comment by LaughtersGrave** [comment]
Has the 4th battle map been fixed to give you at least a few turns to achieve a brilliant victory yet?

**Comment by salexgit** [comment]
Hi LaughtersGrave

I saw that Nicu had committed the corresponding change to the repository, so it will be part of the official game once a new version is released. By the way, I still hold the opinion that the change was wrong - it was intentional behaviour for the "defense" scenario. I am copy/pasting below one scenario description from the "LSSAH" campaign. LSSAH campaign has a lot of scenarios like that, which unlike the offensive scenario, has either TV or L outcome.

--------------
1st SS-Panzer Division LAHSS-Brigadefuhrer Theodor Wisch
The Battle of CaenJuly 8th, 1944Operation Charnwood
On the 8th July the Allies launched Operation Charnwood, an operation to secure the city of Caen.  The Leibstandarte, along with other German units was rushed to the British sector and until the 9th was engaged in repulsing the attack, which cost the life of former Leibstandarte regimental commander and current Hitlerjugend commander Fritz Witt, killed in his HQ by naval gunfire
(Only a TV or a L is possible here.  You must hold out until the last turn and then take the roadblock hex with the reinforcement that shows up to get a TV.)"  

Regards, Alex

**Comment by barsoom1717** [comment]
Alex, I've downloaded the zip file and extracted it with Zip Extractor.  I then clicked on the "index" file, but it just opens the file in Chrome without launching the game.  What am I doing wrong?

Stephen

**Comment by salexgit** [comment]
Hi

Which OS do you use? There should be launch scripts in the root folder - win_chrome.sh, win_firefox.sh, linux_chrome.sh, linux_firefox - so use the corresponding script depending on your OS and the preferred browser.
If you plan to use Chrome, then you must close _all_ open windows before launching the game. This is because Chrome does not allow local file access by default, while the game needs it. 

I have been thinking of creating a nicer package for the game to make it more user friendly, but did not have time to do that. 

Regards, Alex

**Comment by barsoom1717** [comment]
Sorry for being such a dunce, but I'm not seeing those or a "root" folder in the extraction list.  I even did a Ctrl-F and entered in "win_firefox.sh" but got no result on the search.

**Comment by salexgit** [comment]
Hi

It seems that you downloaded wrong/old version of the package. 
1. Open https://sites.google.com/site/openpanzeroffline/downloads
2. Go to the "Offline packages with additional campaigns" section
3. Download "LSSAH + Wacht am Rhein" package. The archive name is openpanzer-2.9.7beta-1.0.5-lssah.zip
4. Unpack and launch the game by using one of the scripts in the root folder. Firefox is a bit simpler option as you do not have to close other windows.

Regards, Alex

**Comment by barsoom1717** [comment]
I give up.  I'm downloading the correct file now, but there is no win_chrome.sh or win_firefox.sh.  There is win_chrome.bat and win_firefox.bat, however trying to open those is getting me no where, as well as trying to open index.html.  Also what is meant by "run this script in your preferred browser" (in this case Firefox).  Again, I seem to be getting no where and am getting extremely frustrated.

**Comment by barsoom1717** [comment]
...and I have Windows 7 on my main computer (Alienware) and Linux on a laptop.

**Comment by salexgit** [comment]
Hi

There are win_chrome.bat and win_firefox.bat files for Windows, and linux_firefox.sh and linux_chrome.sh for Linux. They are the "batch/shell" scripts that should start the game.
Can you be a bit more descriptive than "trying to open those is getting me no where"? I cannot help if I cannot understand what exactly is going on. Can you also elaborate on which browsers you have installed on your system? 

The simplest and the most robust option to launch the game is to install Firefox and open index.html with Firefox; I works on all the platforms. Opening index.html with any browser will not work (for the default security settings) and that is why I created launch scripts for e.g. Chrome.

P.S. I will take the intercontinental flight and most likely be offline for 10-12 hours. Do not give up so easily :)

**Comment by barsoom1717** [comment]
So to run the firefox script, do I right on the Win_firefox.bat file, and try to find firefox in the list, or is there another way to run the script in the firefox browser?




Get Outlook for Android







On Fri, Dec 28, 2018 at 7:11 PM -0600, "salexgit" <notifications@github.com> wrote:












Hi


There are win_chrome.bat and win_firefox.bat files for Windows, and linux_firefox.sh and linux_chrome.sh for Linux. They are the "batch/shell" scripts that should start the game.

Can you be a bit more descriptive than "trying to open those is getting me no where"? I cannot help if I cannot understand what exactly is going on. Can you also elaborate on which browsers you have installed on your system?


The simplest and the most robust option to launch the game is to install Firefox and open index.html with Firefox; I works on all the platforms. Opening index.html with any browser will not work (for the default security settings) and that is why I created launch scripts for e.g. Chrome.


P.S. I will take the intercontinental flight and most likely be offline for 10-12 hours. Do not give up so easily :)

**Comment by barsoom1717** [comment]
Thank you for your patience.




On Fri, Dec 28, 2018 at 7:11 PM -0600, "salexgit" <notifications@github.com> wrote:












Hi


There are win_chrome.bat and win_firefox.bat files for Windows, and linux_firefox.sh and linux_chrome.sh for Linux. They are the "batch/shell" scripts that should start the game.

Can you be a bit more descriptive than "trying to open those is getting me no where"? I cannot help if I cannot understand what exactly is going on. Can you also elaborate on which browsers you have installed on your system?


The simplest and the most robust option to launch the game is to install Firefox and open index.html with Firefox; I works on all the platforms. Opening index.html with any browser will not work (for the default security settings) and that is why I created launch scripts for e.g. Chrome.


P.S. I will take the intercontinental flight and most likely be offline for 10-12 hours. Do not give up so easily :)

**Comment by salexgit** [comment]
Hi

Ok, now I think I understood what is wrong. If you are using Windows, then just double-click the corresponding .bat file as if it were the executable. It will launch the browser with all the necessary parameters.

If you have firefox, then you can just open index.html in the browser (by clicking index.html).

I hope it will work....

**Comment by barsoom1717** [comment]
This is what happens when I double click on win_firefox.bat...
![image](https://user-images.githubusercontent.com/44751544/50532515-de980400-0adf-11e9-9532-f586ec6e7d8d.png)

**Comment by barsoom1717** [comment]
This is what happens when I double click on index.html...
![image](https://user-images.githubusercontent.com/44751544/50532529-261e9000-0ae0-11e9-9c30-6ba13b816079.png)

**Comment by salexgit** [comment]
Hi

Hm, it seems that Windows just ties to "open" the batch script instead of "executing" it; same happens for the index.html file. I cannot really say why it occurs but this is due to the Windows environment itself.
Do you have Firefox installed? Right-click on index.html and opening it with Firefox should do the job.

You can also try Linux, I hope it is more predictable than Windows :)

**Comment by barsoom1717** [comment]
I actually got it to open!  Two questions:  1) Is there a way to save the offline game engine, or will I need to re-do all this if I have to reboot?  2)  Where are the saved game files kept?  When I click on “Load from Disk” it open up in the Desktop library.  However there are no game save files there that I have saved.

**Comment by barsoom1717** [comment]
I answered #2, they are in the Downloads folder.

 

Stephen

**Comment by barsoom1717** [comment]
OK, thanks.  Completed the first scenario.  When you get a chance, is there a way for me to save the offline package files so I don’t have to do all the crazy stuff with the zip files like before?  I have a current problem with the computer hanging, which causes me to have to reboot at least once a day.

**Comment by salexgit** [comment]
Hi Stephen

Which campaign do you play? Just for my knowledge...

Once you get the package downloaded and installed on your computer, that is it; you do not have to re-do the excercise again.

**Comment by barsoom1717** [comment]
LSSAH, the big one.  Again, thank you for all your help.

**Comment by barsoom1717** [comment]
Big show stopper .  I'm in Warta Crossing (I believe its the second scenario in that campaign).  With 5 turns to go, I clicked Next Turn but the only that happened is the turns left ticked down once.  None of the units reset so I could fire or move.  I clicked the Next Turn again, and the same thing happened - number of turns left ticked down to 3, however none of my units could fire or move.

**Comment by salexgit** [comment]
Hi

I suppose that this is same issue as reported in #139. I experienced same problem once and other players reported it as well. As far as I can see, the issue is not campaign or scenario specific, but rather is triggered by a certain unit combination.

Can you please attach the saved game at a turn right before the problem occurs?

The only way to circumvent around the problem is to replay the scenario from the beginning (or from a certain turn X) so that you end up with a different combination of units and their locations.

**Comment by salexgit** [comment]
Hi all

Just for information, all the latest changes are available in the online v3.1.0 beta version: http://openpanzer.net/beta/ 

Thanks to Nicu for releasing it.

**Comment by barsoom1717** [comment]
Are the two new converted campaigns part of the beta now?

 

Stephen

**Comment by barsoom1717** [comment]
That's great.  Thanks.




Get Outlook for Android







On Sat, Jan 12, 2019 at 1:28 PM -0600, "salexgit" <notifications@github.com> wrote:












Hi Stephen


Yes, two new campaigns are includee into beta v3.1.0.

**Comment by barsoom1717** [comment]
Is Zitadelle the last scenario in the new campaign?

**Comment by salexgit** [comment]
Hi

Which campaign are you referring to? As far as I remember, none of the campaigns have Zitadelle as the last scenario.

**Comment by barsoom1717** [comment]
1st SS Liebstandarte Division, one of the new ones.
    On Sunday, January 20, 2019, 2:40:36 AM CST, salexgit <notifications@github.com> wrote:  
 
 
Hi

Which campaign are you referring to? As far as I remember, none of the campaigns have Zitadelle as the last scenario.

**Comment by barsoom1717** [comment]
Yes.  Let me see if I cab find a save game vefire the last turn to send you.




Get Outlook for Android







On Sun, Jan 20, 2019 at 7:27 PM -0600, "salexgit" <notifications@github.com> wrote:












Hi


Operation Zitadelle is not the last scenario in the LSSAH campaign. Do you have an issue with moving to the next scenario?

**Comment by barsoom1717** [comment]
Here it is. 




Get Outlook for Android







On Sun, Jan 20, 2019 at 8:23 PM -0600, "salexgit" <notifications@github.com> wrote:












Hi


Ok, it seems that you have experienced an issue reported by some people and which I also faced once. Once you capture the last victory hex, the game just "freezes" instead of moving to the next scenario. I thought that the issue was already fixed, but maybe not...


If possible, can you please upload here the saved game just before capturing the victory hex?

**Comment by salexgit** [comment]
Hi

It seems that the attachment is missing, at least I cannot see any.

**Comment by barsoom1717** [comment]
Github won't let me attach it.

**Comment by barsoom1717** [comment]
Got another way I can get it to you?  Says "We don't support that file type".

**Comment by salexgit** [comment]
Hi

To upload saved game, compress it with e.g. zip archiver and upload here. Github accepts .zip archives.

**Comment by barsoom1717** [comment]
Ok




Get Outlook for Android







On Sun, Jan 20, 2019 at 11:03 PM -0600, "salexgit" <notifications@github.com> wrote:












Hi


To upload saved game, compress it with e.g. zip archiver and upload here. Github accepts .zip archives.
