### ISSUE TITLE
UI issues in the latest version

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#178]
Hi Nicu

I decided to make a several post on identified UI issues, even though it relates to #176. 

- Transport and leader icons in the inspect window. I noticed that leader and transport icons have been moves to the top and bottom corners on the left hand side. However, it works only in Chrome. If you open inspect window in IE or Firefox, those icons will overlap with the main unit icon. As a side comment, I liked more when those icons were on the right hand side, just a matter of taste,

- Strategic map. Strategic map window does not work properly anymore in IE; no issue in Firefox and Chrome. So, if you switch to the stregic mode in IE, there will be just a small portion of the map in the bottom right corner. 

- Air mode. There are several minor logical flaws in how "air mode" button works in relation to other actions on the map. 
- Example 1: a) activate air mode -> air units will become highlighted; b) click any groun unit -> air mode button becomes deactivated but air units will remain highlighed;   
- Example 2: a) click any air unit -> air mode button becomes activated but other air units are not highlighted

**Comment by nicupavel** [comment]
> * Transport and leader icons in the inspect window. I noticed that leader and transport icons have been moves to the top and bottom corners on the left hand side. However, it works only in Chrome. If you open inspect window in IE or Firefox, those icons will overlap with the main unit icon. As a side comment, I liked more when those icons were on the right hand side, just a matter of taste,

Works fine on my firefox 57.0.4. I moved those icons because I was having to scroll the unit information 
to reach leader info on mobile app/small screen which was very annoying. 

> * Strategic map. Strategic map window does not work properly anymore in IE; no issue in Firefox and Chrome. So, if you switch to the stregic mode in IE, there will be just a small portion of the map in the bottom right corner.

What IE version is that ? I don't have any windows machines/vm to test on I was hoping IE will catch up eventually with other browsers.

> * Air mode. There are several minor logical flaws in how "air mode" button works in relation to other actions on the map.
> * Example 1: a) activate air mode -> air units will become highlighted; b) click any groun unit -> air mode button becomes deactivated but air units will remain highlighed;
> * Example 2: a) click any air unit -> air mode button becomes activated but other air units are not highlighted

All these are related to "partial rendering" I don't clear/redraw the entire viewport just around the selected unit. I saw it and didn't bother me much to force a full render on air/ground change. Probably with current devices computing power full render will be fine.

**Comment by salexgit** [comment]
Hi again

Here are some more ideas on minor but useful UI improvements:
- There is a scenario intro message box shown in the beginning of each game, size of which however is a bit small. Some scenarios have a lot of introduction text and it would be nice to see it without scrolling the message box. It seems that there is enough space to increase this message box size even for the mobile app version.
- Speaking further of the scenario introduction text, it is shown only once when a new scenario starts and there is no way to see it again. However, some scenario descriptions contain useful instructions  and hints. What if we add a possibility to see the scenario description again in e.g. strategic map mode?

**Comment by nicupavel** [comment]
The second one is being take care of with next beta it's a good idea. For the larger one it's also a good idea, but maybe I'm nostalgic because it looks similar to the original one from Panzer General 2.

P.S. I fixed the issue with Leader/transport/embark icons on unit info, it's also happening on iOS app and iOS safari.

**Comment by salexgit** [comment]
Hi again

As a follow-up comment for the scenario description window, can you please enforce "\n" character while formatting the text? When you select a particular scenario on the scenario description list, the "\n" character is obeyed. However, when you move from one scenario to another, exactly the same text is shown without accounting for the "\n" character. I assume that different formatting rules are applied.

Regards, Alex

**Comment by nicupavel** [comment]
Hi,

Yes in the next beta the window is as large as the minimal mobile resolution permits (iPhone4).
As for the flag, I will need to redesign the entire campaign select screen as adding images to select options tags is not supported on all browsers.

The \n issue is because the scenario/campaign selection uses a <pre> tag I think while ingame window does not.

**Comment by salexgit** [comment]
Hi Nicu

Regarding the main country flag on the campaign list, this was just a minor improvement. We can abandon this idea if it is not supported by all the browsers.

Concerning text formatting in the scenario description window, here are my findings:
- For some reason the same scenario text is added to the campaign JSON file and into the scenario list file; maybe it is just easier for the game engine.
- Scenario description text in the scenario list file is formatted using "<br>" tag, and that is why it looks correct.
- However, same text in the JSON file uses "\r\n" tags, which are of course ignored by the HTML rendering engine. I changed manually "\r\n" into "<br>", and it worked.
- You can observe this behavior by opening the first scenario of any campaign in the campaign mode and in the standalone mode - the resulting formatting will be different since there are no "<br>" tags in the former case.  

I assume that the fix is very simple, we just need to modify the campaign-convert.py script so that it uses "<br>" tags while generating the JSON file.

Regards, Alex
