### ISSUE TITLE
New bugs?

### ISSUE THREAD

**Issue by barsoom1717** [nicupavel/openpanzer#188]
Couple of things I'm finding...
--If you move a unit to the same hex (by accident of course) where a unit is you just deployed, it wipes out that unit and you don't have it in your inventory any longer...
--I have some Fi 167 A-0 that I want to upgrade to  He-111s.  Everytime I do so, when I deploy them they have no fuel, hence I can't move them at all.  I've also tried changing them to Do-172 and gotten the same result.  The search bar at the bottom shows they have 135 gallons, but once deployed it goes to zero.
--Maybe not a bug, but hate the fact how the game reinforces the its side - behind my lines!!!  I mean really?  We are not talking about just paratroopers either.
--I think there is one more but can't remember right now.  Will add it later.

**Comment by salexgit** [comment]
Hi

If I have time, I will check issues 1 and 2. 

Regarding "issue" number 3, re-inforcement behind the lines, this is not a bug. All units in a particular scenario can either appear immediately or can be "deployed" later at a particular turn.  In most cases this feature is used to provide more units to your army. However, sometimes scenario designers  use this feature to make your game "more interesting" by deploying units behind your lines. I tend to agree that it is a bit annoying and one could argue that it is not realistic either. 
Also note that one of the reasons why enemy units may end up behind your lines is because the front line moves too fast. To balance the game, a scenario designer might decide to supply more enemy units at turn X as opposed to deploying all the units immediately in the beginning of the game, but nobody can predict where exactly you will be by turn X.

Regards, Alex

**Comment by barsoom1717** [comment]
On number 2, I discovered that if I upgraded to a plane "above" the He-111, there are no problems (like the Me410).

**Comment by salexgit** [comment]
Hi

Regarding issue #2, can  you please attach here saved game so that we can try to reproduce the issue?
