### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by Yefimov** [nicupavel/openpanzer#191]
Hello, it's too bad that this game doesn't have russian translation. How I can help to fix this?

**Comment by salexgit** [comment]
Hi

Translating interface into other languages should not be complex. However, 90% of text is campaign and scenario descriptions, which are coming from the SCN files and which do not support multi-language support at all. In short, we are captives of the framework in which only one language at a time is supported. Translating everything into e.g. Russain means that a separate application have to be created. 

Regards, Alex

**Comment by nicupavel** [comment]
That would be quite a task. There isn't much on UI to translate (although some text of different lengths might make some elements look bad) but there is a lot in scenarios description.

I will compile some archive to make an idea of the work involved.

**Comment by salexgit** [comment]
Hi Nicu

Interface localization should be relatively simple task because we do not have much text indeed. There are also various HTML and CSS tricks allowing for that.

Localizing campaigns/scenarios is a more challenging task. Firstly, somebody has to translate and maintain them. Then, it is not entirely clear how to organize input data because there is only one .TXT file associated with e.g. scenario description. Well, we can assume that .TXT will be always English and .TXT.DE will be German, .TXT.RU will be Russian etc. The compile script can merge everything into the multi-language .XML file. So, it is feasible but it is a non-trivial amount of work :)
