### ISSUE TITLE
AAA Spawns

### ISSUE THREAD

**Issue by CommanderDeltor** [nicupavel/openpanzer#199]
I'm not sure if this has been happening to others, but in some scenarios during campaigns, the battle will load all enemy units as some sort of AAA. This has happened at least five times to me.

**Comment by barsoom1717** [comment]
Happened to me in the Student scenario when I started re-doing the campaign a couple of weeks ago.




Get Outlook for Android







On Thu, Feb 21, 2019 at 8:16 AM -0600, "CommanderDeltor" <notifications@github.com> wrote:












I'm not sure if this has been happening to others, but in some scenarios during campaigns, the battle will load all enemy units as some sort of AAA. This has happened at least five times to me.

**Comment by salexgit** [comment]
Hi CommanderDeltor 

Can you please clarify which campaign and which scenario are you referring to? Note that since OpenPanzer AI cannot be as smart as a human, some scenarios indeed have more or stronger units allocated to another player to balance the game. In some scenarios, more units are added to AI in form of "re-inforcements" spawning units in locations where you would not expect them. 

Regards, Alex

**Comment by CommanderDeltor** [comment]
Alex, 
As of this writing, it has occurred in:
Student
Crossing the Schelde
Maginot Line Garrison
Operation Sealion Training
Operation Marita
Crossing the Dneper
Holland
Advance to Dunkirk
Vevi
Zhitomer
Gran Bridgehead

To clarify, the problem that is occurring is that every AI-controlled unit is a 2Flak AAA gun or an M16 AAA gun. This only seems to happen in the campaign mode.

**Comment by barsoom1717** [comment]
Agree with what ComnanderDeltor said about the details.  For me it only happened in the Student game.




Get Outlook for Android







On Thu, Feb 21, 2019 at 8:24 PM -0600, "CommanderDeltor" <notifications@github.com> wrote:












Alex,

As of this writing, it has occurred in:

Student

Crossing the Schelde

Maginot Line Garrison

Operation Sealion Training

Operation Marita

Crossing the Dneper

Holland

Advance to Dunkirk

Vevi

Zhitomer

Gran Bridgehead


To clarify, the problem that is occurring is that every AI-controlled unit is a 2Flak AAA gun or an M16 AAA gun. This only seems to happen in the campaign mode.

**Comment by salexgit** [comment]
Hi

This is wrong/strange of course... 
The symptoms are very similar to what I reported once in #184. In short, OpenPanzer loads equipment file based on the country index ID. If it fails to load it, then instead of showing the error message, it ends up showing those Flak units. So, either it is a bug in the game engine or you have a blocker installed on your computer that prevents the equipment file from being loaded. Do you have this problem while playing the Web version or the mobile version? 

Regards, Alex

**Comment by CommanderDeltor** [comment]
Alex, 
This occurs on the Web version. However, I do not have any blockers on my computer, and I have noticed two other things. 
1. The problem occurs MUCH more frequently in the Das Reich campaign, with all scenarios after the first glitched one loading either the M16 AAA unit or the 2flak unit. 

2. Reloading the page, at least in Operation Marita, caused the M16 AAA units to turn into 2flak units. 

Also, (and this is just me), the Operation Sealion scenario in the Das Reich campaign had my core massacred by the Italian navy. Perhaps increasing German naval units in that scenario, or decreasing Italian naval units might help?

Respectfully, Deltor

**Comment by salexgit** [comment]
Hi Deltor

Firstly, let's not mix different issues in the same discussion thread. The main developers already asked me to check "Operation Sealion" scenario and I plan to do it asap. I cannot recall any problems with that scenario, but due to changes in AI it could become more challenging. 

Back to the main issue... I heavily suspect that the root cause is that the equipment file is not loaded, but I cannot say what the actual reason is. If there are no blockers at your computer, then it could be indeed some bug in the code. 

Regards, Alex

**Comment by CommanderDeltor** [comment]
Alex,
Thank you very much. I started playing Panzer General Assault 3D back when I was about five or six, and when I found this game a few years ago I was ecstatic. Hopefully this gets fixed at some point, and I can't wait for what you guys do next with it. 

Best of luck, 
Deltor

**Comment by salexgit** [comment]
Hi

Since I cannot say when the main developer will take a look at this issue, do please consider using "offline" package for desktop computers. 
https://openpanzer.itch.io/panzermarshal

If you do not experience any issues with the offline packages, then the problem is most likely due to some local blocking and/or failures to load equipment files.

**Comment by nicupavel** [comment]
A save game would help so I can check. Also the Developer Console from browser should list some errors if equipment load fails.

**Comment by CommanderDeltor** [comment]
This save file is from Kherson. This time it was the Romanian units the player controls which turned into flak units. Hopefully this helps. 

[(Campaign) Kherson Turn 1 Wed Feb 27 2019 4_12_17 PM.zip](https://github.com/nicupavel/openpanzer/files/2912647/Campaign.Kherson.Turn.1.Wed.Feb.27.2019.4_12_17.PM.zip)

**Comment by nicupavel** [comment]
Problem is that the save game doesn't show where the error happened since the units are already saved. I would need the save game from the previous scenario last turn or close to end to check it out.

**Comment by salexgit** [comment]
Hi Nicu

Can you please consider adding (at least) some error message if the game fails to load the equipment file? If I remember right, you have a similar error message if the map image file cannot be loaded. 
My point is that it is very obscure that when the game engine fails to load the equipment file, it just continues as nothing serious had happended creating later even more confusion when a player sees all those Flak units. 

@CommanderDeltor: Did the problem occur with the online version or offline? 

Regards, Alex

**Comment by dygage** [comment]
so found your new release and got very excited but after  I got a bv on the first mission of the German world campaign on historical difficulty, the second mission. Loaded fine and I got my prototype unit, but all of the enemy units were anti aircraft guns with no other kind of units... Ive seen this issue several times before in random scenarios, they almost seem to be random flukes because if I remember correctly, I would try to do it again I.e. beat the prior mission 8th same victory on same difficulty and it works the second time I think, but like a previous commenter, its only been in the campaign... I'm going to try winning the first mission. Again with a bv on same difficulty and see if it happens again and I'll let you know what happens... And I'm playing your browser version using an android phone

**Comment by salexgit** [comment]
Hi

To my best knowledge, this is indeed a random problem, which according to the main developer occurs mostly on mobile platforms when the browser environment runs out of memory. I cannot really comment whether it is going to be fixed in the next release and/or whether there will be a way to circumvent around this issue. 
The best recommendation I have is to save your game right before you take the last victory hex, so that you can open your scenario on the desktop computer.
