### ISSUE TITLE
Some minor issues...

### ISSUE THREAD

**Issue by wrleskovec** [nicupavel/openpanzer#203]
1. I noticed that I can recruit units that I shouldn't be able to recruit by hovering over them and getting a new unit. This allows you to clone rewarded elite units. 
2. There are issues with units disappearing with deployment and allowing you to deploy over them. 
3. On the main das reich campaign it crashed for me saying that drseal06 or something was not found after the maginot campaign BV.
4. I'm not sure if its intentional but you can also scout with undo by moving your unit into areas you think might contain enemies then undoing if it does not contain enemies.
5. This may have been fixed already but I've noticed that some MGs can indirect fire against aircraft.
6. I was able to ford the river with all my units in mission 4(the belgium one I think) of das reich. Again I'm not sure if this is intentional or has something to do with broken bridges technically.

Other issues with the game that are less technical are mostly about the difficulty and some major unit imbalances:
1. 81mm allied mortars are very strong considering the cost. I would rate them as better than howitzers in many situations. This makes the Big Red campaign very easy because most of the challenge is quickly wading through entrenched units and mortar spam makes this easy.
2. There tends to be a huge drop off in difficulty after the first couple of missions. I was usually finishing missions before many of the reinforcement events in the scenario triggered. I still find it kind of hilarious that elite polish cavalry has been the hardest to kill unit in the game so far. I have only played the Das Reich and Big Red campaigns so far though.
3. High soft damage tanks tend to be much more useful than high hard damage tanks and this makes weird gamey armies built around flampanzer II and m3 grant tanks. On some maps the ai has no real counter to soft damage tanks and this allows the player to easily chain kill until ammo/supply exhaustion.

If you could post the full unminified/compiled source code on github it might be easier to fix bugs in your code. I'm not sure if you have the source somewhere else or you decided to close source it though?

**Comment by salexgit** [comment]
Hi

Thanks for your feedback. Here are some comments from my side as some of the issues were also discussed offline.

1-3. I suppose that this is somewhat similar to issue #207. We deprecated one scenario from the DasReich campaign, but we unintentionally broke the next scenario index values. It should be fixed in the next release (it is already fixed and committed and should be ready soon via online beta).
1-4. If you can scout and undo your movement, then it is wrong of course. As far as I remember, and that is what I also experienced, you should not be able to undo the move if you scout enemy units. However, either we broke something in the code or there is a weird coincidence of facts allowing it in a particular case. I will double check it if I have time.

2-2. Regarding the scenarios, campaigns and difficulty. Firstly, most scenarios and campaigns are not designed by us, but rather are coming from the PGII community. We can of course do some fixing and tuning, but this is merely on the case by case basis. Nevertheless, I tend to agree that almost in all campaigns first scenarios are more difficult, but this is (partially) due to the fact that the game mechanics is a bit different comparing to PGII making late scenarios easier. Unlike in PGII, we do not support the concept of the deployment and supply hexes, i.e. you can deploy as many units as you have. In PGII, there was a way to create a bottleneck in how many units you can deploy per turn; and on the contrary to PGII, this game allows to deploy all the units in one turn over the same hex. In other words, once you play several scenarios and build a larger army, you can leverage all the units you have.
I had an offline discussion with the main developer, and as far as I understood, this will be enhanced in next releases, i.e. we will also follow the deployment/supply hex model thus making late scenarios more challenging.   

Regards, Alex

**Comment by FT-Diomedes** [comment]
Too bad to hear that you are fixing the deployment/supply hex model. For me, the one thing that makes this game really enjoyable over the course of a campaign is building up your unit, training your core units, and progressing with them. I would much rather enhanced support for more core unit deployment - and far fewer non-core units. That is the approach I take when I mod the old Blitzkrieg game (still playing it since 2002 - these old games have so much more staying power than the new ones): let the player determine the composition of their core units, but give them very little non-core unit assistance (except for specialized units that may be essential to completing a map, such as a bridge unit). As I get to the later game, I have essentially stopped using the non-core units except when I have no choice at all.

**Comment by barsoom1717** [comment]
I agree.  Would rather have more control over core units and less auxillaries.




Also, even though I wanted the overstrength option, it should be dialed back to no more than 15.  I have some panther tanks at strength 20+, and the only thing that stops them from destroying and overrunning enemy units, is them running out of ammo or fuel.




Get Outlook for Android







On Mon, Apr 22, 2019 at 5:29 PM -0500, "FT-Diomedes" <notifications@github.com> wrote:












Too bad to hear that you are fixing the deployment/supply hex model. For me, the one thing that makes this game really enjoyable over the course of a campaign is building up your unit, training your core units, and progressing with them. I would much rather enhanced support for more core unit deployment - and far fewer non-core units. That is the approach I take when I mod the old Blitzkrieg game (still playing it since 2002 - these old games have so much more staying power than the new ones): let the player determine the composition of their core units, but give them very little non-core unit assistance (except for specialized units that may be essential to completing a map, such as a bridge unit). As I get to the later game, I have essentially stopped using the non-core units except when I have no choice at all.

**Comment by salexgit** [comment]
Hi FT-Diomedes

Firstly, since auxiliary units are already deployed in the beginning of the game, there is no tradeoff between core and auxiliary units. The only question is whether game model should allow deploying as many core units as you have in one turn (as in the current implementation), or whether there should be a way to restrict it if needed (as PGII behaves). It does not mean that all the scenarios will have this restriction.

The background is a simple fact that we borrow and use scenarios developed for the PGII game model, in which a core unit deployment restriction can be enforced. And if we do not, then it can result in a quite noticeable imbalance. I personally found late scenarios from DasReich campaign too easy and boring just because you can deploy the whole army in one turn over the same tile, whereas this is not what the scenario designers intended for.  

Referring to the barsoom comment, I agree that it is not so difficult to get units at strength 20 making them unstoppable. I discussed some time ago with the main developer on whether we should limit it to 15 as in PGII, or whether we should make overstrength more expensive and/or whether there should be some exponential model on how much experience you should get to be able to overstrength to the next level.
