### ISSUE TITLE
Some minor problems

### ISSUE THREAD

**Issue by campaignbuff** [nicupavel/openpanzer#204]
Awesome upgrade but still there are some problems:
Élite polish cavalry unit definitely op
Some allied weapons are op es. mortar
Furthermore I quite sad to see that we went back to having just 2000 credits in the scenarios... can something be done about it?
Anyway you deserve my compliments for the awesome game you created and the evolution it underwent in this years.
Keep up the good work

**Comment by barsoom1717** [comment]
A trick I learned is delay capturing the last victory hex until the last turn left for tactcal victory.  Since you get 375 per turn, you can pile up a lot of prestige in those first two scenarios.  It won't change the game path either.




Get Outlook for Android







On Fri, Mar 22, 2019 at 3:22 PM -0500, "campaignbuff" <notifications@github.com> wrote:












Awesome upgrade but I was sad to see that we went back to having just 2000 credits in the scenarios... can something be done about it?

**Comment by campaignbuff** [comment]
You misunderstood what I meant my friend, I mean that with the previous update when you played  in the single scenarios the player started with 8000 prestige to create from the ground up a core army,  now sadly nicu (the developer) went back to the original 2000 prestige that in my opinion makes the gameplay a lot less enjoyable in that mode.

**Comment by barsoom1717** [comment]
Ah.  Got it.  I always play the campaign, since that is the only way for your core units to gain experience.  I incorrectly assumed you were playing the campaign as well.




Get Outlook for Android







On Fri, Mar 22, 2019 at 4:31 PM -0500, "campaignbuff" <notifications@github.com> wrote:












You misunderstood what I meant my friend, I mean that with the previous update when you played  in the single scenarios the player started with 8000 prestige to create from the ground up a core army,  now sadly nicu (the developer) went back to the original 2000 prestige that in my opinion makes the gameplay a lot less enjoyable in that mode.

**Comment by campaignbuff** [comment]
I do i do and there isn’t much I can complain in campaign mode except for some issues, still this game made enormous leaps forward. Once It was barely playable now is a marvellous game

**Comment by salexgit** [comment]
Hi campaignbuff

Prestige amount for the standalone scenarios has been a painful topic and I also spent a lot of time with the main developer discussing how we should implement it. If you assign too much prestige, the scenario might end up a bit boring as you will of course defeat any enemy army. If we do not allocate enough prestige, then we start receiving complains about how difficult it is. Furthermore, it also varies a lot from a scenario to a scenario how much prestige you need to win.

The way it was implemented for PGII is that you can control how much prestige you can have. In other words, every time you start a new scenario in a standalone mode, you could specify whether you start with default 100 or any other value.

Regards, Alex

**Comment by sprinkler** [comment]
Current version does prestige autobalancing for both sides when playing standalone scenarios. If you get only 2000 prestige, which is the minimum, it means that the other side has less units and reinforcements on map.
The other side will receive a prestige equivalent of your extra units costs.
As another scenario balance, the new units that you buy now automatically come with experience set to scenario average units experience. This is quite important and you might fare much better with experienced units and less prestige than 0 experience units and much more prestige. A 0 experience unit will most likely be destroyed by a 500+ experience unit.

**Comment by nicupavel** [comment]
Current version does prestige autobalancing for both sides when playing standalone scenarios. If you get only 2000 prestige, which is the minimum, it means that the other side has less units and reinforcements on map.
The other side will receive a prestige equivalent of your extra units costs.
As another scenario balance, the new units that you buy now automatically come with experience set to scenario average units experience. This is quite important and you might fare much better with experienced units and less prestige than 0 experience units and much more prestige. A 0 experience unit will most likely be destroyed by a 500+ experience unit.

**Comment by campaignbuff** [comment]
Thanks very much to you all, now i’ve undestrood the mechanics, still a bit sorry not to be able anymore to buy a moltitude of units but if it serves the balancing, I’m fine with it.
