### ISSUE TITLE
My firtsth opinions About 3.2.1 beta

### ISSUE THREAD

**Issue by Philip799** [nicupavel/openpanzer#210]
- game works ideal on PC, better on web page, but has some issues with screen compatibility (small screen size), fixing when change somethink in setup.
- on Android ver. Sometimes hangup when turn ending. 
- on pc ver I havent seen any bugs. 
- I have problem with embark para units on airfields
- some airfields without flags can be taken and use. 
- It isna good idea when enemy left strategics points and attack leaving digin positions. 
- i think some mechanics solutions can be taken not from panzer 2, but from steel panthers. It can be a good think in some reasons.

**Comment by salexgit** [comment]
Hi

Firstly, thanks a lot for your feedback...

With regards to the AI behaviour, I also discussed with the main developer some time ago that new AI has a proclivity of abandoning strategic points and/or leaving positions with high entrenchment level. As far as I understood, this should be fixed in the future.

Game mechanics is another interesting point. So far we have been trying to follow PGII rules, but it is of course would be nice to try other rules. In principle, it should be possible to collect game rules/mechanics in a form of a ruleset, so that one can choose which ruleset you want to follow. However, I am afraid that it is not going to implemented in the near future. 

Regards, Alex

**Comment by Matimbo** [comment]
The only bug I see is it hanging after a save using an IPad.   You have to close the app completely, and even then it can take two or three times to engage.  Super game, very excited to see it after enjoying PGII so long ago.
