### ISSUE TITLE
44 infantry?

### ISSUE THREAD

**Issue by GavinLiam** [nicupavel/openpanzer#216]
in the campaign big red one, it says upgrade your 43 infantry to 44 infantry but i cannot find 44 infantry only 44 glider, armored, and parachute infantry. which is 44 infantry referring to? thanks

**Comment by salexgit** [comment]
Hi

Which scenario description are you referring to? There is indeed no "44 Infantry", but there is "44 armored infantry" unit type (similar to German Panzergrenadiers), so I suspect that there is a typo in the scenario description.

**Comment by GavinLiam** [comment]
it is in the omaha beach scenario. so does that mean i should upgrade my 43 infantry to 44 armored infantry?

**Comment by salexgit** [comment]
Hi

Ok, the confusing part is that scenario instructions say to "upgrade 43 infantry to 44 infantry still with GMC2.5 transports". The problem is that neither "44 infantry" exists nor "44 armored infantry" makes any sense with GMC2.5 transport. 

Good news is that scenario instructions and recommendations can be ignored, at the end you are free to choose/buy any unit type you like. Meanwhile, I will investigate further where this discrepancy comes from. It could be just a typo or it could be the case that the scenario description was written for the equipment file that indeed has "44 infantry" unit type.

Regards, Alex

**Comment by GavinLiam** [comment]
okay thank you very much
