### ISSUE TITLE
Empty unit list

### ISSUE THREAD

**Issue by FT-Diomedes** [nicupavel/openpanzer#218]
Great game and very enjoyable!

I do, however, have a few issues.

1. It crashes a lot, especially during deployment mode. That's to be expected and it doesn't really bother me (I save games reflexively).
2. On the Bizerte map, I am unable to progress because the game does not seem to have recognized that I have deployed all my core units. The bar at the top that shows units also has disappeared. It works up until the point when I deploy my units, but once I have deployed them all, the deployment boxes remain visible (as if I am still in deployment mode), while that bar disappears. I can move units, although the movement range view is not available (as is typical during deployment mode), but cannot initiate any attacks.

Any assistance anyone can offer would be most appreciated.

**Comment by FT-Diomedes** [comment]
I got around this by not deploying my HQ unit and dismissing the helpful bar across the top.

I am not sure why it did this. 

Anyway, I am now four turns in and getting increasingly annoyed at the silly scripting that is causing German reinforcements to span behind or in the middle of my front line troops. This is one of those issues that better map design should alleviate. Also, I wonder why I am fighting SS Infantry in Tunisia. I don’t recall them serving in that theater.

**Comment by salexgit** [comment]
Hi

Enemy troops appearing behind or in the middle of the front line is just the way the scenario designer decided to make your game more interesting/challenging; but I agree that it could be a bit annoying and maybe it is not very realistic either.

Referring to the first issue, can you please upload a saved game so that we can check whether it is an existing bug or something new?

Regards, Alex

**Comment by FT-Diomedes** [comment]
I managed to get past Bizerte by not deploying the HQ unit. I am getting the same issue on the Gela mission.

Cloud Saved Game ID is 91d067efda866a1a755e93f6843aa34c

**Comment by salexgit** [comment]
Hi

I loaded the saved game that you provided, what is wrong with it? At least the saved game works fine unless I am missing something.

**Comment by FT-Diomedes** [comment]
Normally, I could have the unit bar across the top open. In this save game, it goes into deployment mode whenever that bar is visible. This makes it very difficult to systematically go through and see which units have moved and attacked.

**Comment by FT-Diomedes** [comment]
![image1](https://user-images.githubusercontent.com/49885557/56657857-0d298400-6667-11e9-876f-02e935577dc4.png)
![image2](https://user-images.githubusercontent.com/49885557/56657858-0d298400-6667-11e9-8940-920e9d6f3971.png)
![image3](https://user-images.githubusercontent.com/49885557/56657859-0d298400-6667-11e9-804e-f5e54b4767ad.png)

Okay, here are three images that show the problem. The first one is from the Liebstandarte campaign. It shows the units currently deployed on the map across the top. This makes it very easy to cycle through a large number of units in a systematic manner. For whatever reason, this is not available in the Big Red 1 campaign, without opening up the deploy units hexes (even though I have no units available to deploy).

**Comment by salexgit** [comment]
Hi

Now I got it. I did not realize that the top window does not show the unit list as it should be. 

I was a bit confused when you reported that the problem is with the Bizarte map. The map and the scenario is fine, it is the game engine that for some reason does not show the unit list. Interestingly enough, if you open the "Gala" scenario in the standalone mode, then everything looks fine. So it seems that there is something in the saved game that causes such a weird behavior. 

I will rename this discussion thread title to avoid confusion...

Regards, Alex
