### ISSUE TITLE
v3.2.3 Release (beta)

### ISSUE THREAD

**Issue by nicupavel** [nicupavel/openpanzer#220]
Version 3.2.3 is a fix update for the large batch of campaigns added in 3.2.2 version.

Along with campaign fixes I also added the following features:

1) Implemented Sell Unit  in equipment window. You can only sell your core army units and get prestige back with a certain small penalty.
2) Many of the reported problems with wrong units or flak units come from the fact that players buy units from other countries instead of campaign playing country. This has been temporarily disabled.
3) Fixed number of turns per day report to follow how scenario designed intended.
4) Added small tooltips for Objectives, No Ammo/Fuel and Air/Naval transports to make it easier for players to find these. Each tooltip can be hidden on tap/click and can be shown again by showing Hexes lines (H key)
5) Added keyboard shortcuts:

E	- Embark/Disembark
M	- Mount/Dismount
S	- Supply
R	- Replacements
O	- Over-strength
U	- Undo last move if possible
N	- Select Next Unit
P	- Select Previous Unit
A	- Toggle Air/Ground Mode
H	- Toggle Hex marks on/off
B	- Toggle Buy/Upgrade menu
I	- Toggle Inspect unit
Z	- Toggle Strategic Map
Esc - Deselect Unit. With no unit selected toggles Main Menu
6) Added extra scrolling space at the bottom of the map so the unit info window doesn't cover the map, making it annoying to select bottom units.
7) Fixed an issue where a reinforcement unit could not spawn resulting in game errors.
8) More units types can no be air embarked, as in original Panzer General 2

Previous beta:

Version 3.2.2 it's a big content update. There are 5 new campaigns with medium difficulty level but with a lot of fun and historical information.

1) German World Campaign a well detailed gigantic campaign with 50 scenarios
2) United States World Campaign a semi historical campaign with 25 scenarios which has a few USA vs Soviet Union hypothetical scenarios.
3) United Kingdom World Campaign a fun historical campaign that also portraits battles in eastern Africa against Italian Army and then continues in Europe until end of war over 24 scenarios
4) Italian Afrika Korps Campaign a 31 scenario campaign that focuses on battles that took place on African soil ported by Alexander Sayenko.
5) Romanian Campaign In an effort to reclaim old territories lost to Soviet Union,  Romania mustered more combat troops for the Nazi war effort than all of Germany's other allies combined​. This 17 scenario historical campaign presents the course of battles fought by Romanian army from the beginning of Operation Barbarossa, Stalingrad disaster and finishing with ousting of pro-nazi regime and continuing the fight along Soviet Union against his former ally.
There are also a few fixes for equipment, ui and previous campaigns.

Web: http://panzermarshal.com/beta/
Offline: https://openpanzer.itch.io/panzermarshal

**Comment by barsoom1717** [comment]
Nicu,


On the German World campaign, are there forking paths based on victory types (BV, V, or TV)?




Stephen




Get Outlook for Android







On Tue, May 14, 2019 at 2:05 AM -0500, "Nicu Pavel" <notifications@github.com> wrote:












Version 3.2.2 it's a big content update. There are 5 new campaigns with medium difficulty level but with a lot of fun and historical information.



German World Campaign a well detailed gigantic campaign with 50 scenarios

United States World Campaign a semi historical campaign with 25 scenarios which has a few USA vs Soviet Union hypothetical scenarios.

United Kingdom World Campaign a fun historical campaign that also portraits battles in eastern Africa against Italian Army and then continues in Europe until end of war over 24 scenarios

Italian Afrika Korps Campaign a 31 scenario campaign that focuses on battles that took place on African soil ported by Alexander Sayenko.

Romanian Campaign In an effort to reclaim old territories lost to Soviet Union,  Romania mustered more combat troops for the Nazi war effort than all of Germany's other allies combined​. This 17 scenario historical campaign presents the course of battles fought by Romanian army from the beginning of Operation Barbarossa, Stalingrad disaster and finishing with ousting of pro-nazi regime and continuing the fight along Soviet Union against his former ally.


There are also a few fixes for equipment, ui and previous campaigns.

**Comment by past-caring** [comment]
This is a 3.2.1 issue but I don't think it's been discussed - so probably still present in 3.2.2....

Das Reich campaign. After Prochorovka I move to Counter Attack on the Mius. I can deploy my units, but on the next turn I cannot engage in combat with them. They can move but cannot attack. Also both the German and Soviet deployment hexes remain highlighted in grey. Ending the turn does not change this. Do not think the issue is Counter Attack on the Mius - previously I got through this scenario but then got it on Fourth Battle of Kharkov. That's why I went back to previous save of Prochorovka. As part of the problem the unit bar showing my units disappears and cannot be brought back. Samsung S7. Android version 8.0.0.

**Comment by nicupavel** [comment]
> Nicu, On the German World campaign, are there forking paths based on victory types (BV, V, or TV)?

Yes there are, you can go to Campaign screen and click on the "map" button next to ok / cancel buttons to see how scenarios progress.

**Comment by nicupavel** [comment]
> This is a 3.2.1 issue but I don't think it's been discussed - so probably still present in 3.2.2....
> 
> Das Reich campaign. After Prochorovka I move to Counter Attack on the Mius. I can deploy my units, but on the next turn I cannot engage in combat with them. They can move but cannot attack. Also both the German and Soviet deployment hexes remain highlighted in grey. Ending the turn does not change this. Do not think the issue is Counter Attack on the Mius - previously I got through this scenario but then got it on Fourth Battle of Kharkov. That's why I went back to previous save of Prochorovka. As part of the problem the unit bar showing my units disappears and cannot be brought back. Samsung S7. Android version 8.0.0.
> 
> ETA 3.2.2 not yet showing on Google Play so I am stuck with 3.2.1 anyway.

Mobile apps will be published after we have better tested the published campaigns.
There seems to be a lot of issues on Android recently, if you have a cloud save with the issue please let me know. I'm gathering the issues to fix them in the next release

**Comment by past-caring** [comment]
Nick - I have a cloud save but I will progress the campaign closer to where the issue occurs and then save and send....

**Comment by barsoom1717** [comment]
Thanks.




Get Outlook for Android







On Tue, May 14, 2019 at 10:32 AM -0500, "past-caring" <notifications@github.com> wrote:












Nick - I have a cloud save but I will progress the campaign closer to where the issue occurs and then save and send....

**Comment by MansteinlovesGuns** [comment]
Seems like it wont work? I got to Holland level 4 of LIebstandarte and then after passing the level it crashed and I cant enter beta online again. When I tryI get a message image cant load

**Comment by Philip799** [comment]
1. Can you change this long ID to standard login, or some shorten, to cloud save? 

2. In 3.2.2 are added only campaigns with maps? 
There are some game mechanics change on 3.2.2? In devblog I cant find this. 

More mechanics changes can do a great things with this game.

**Comment by barsoom1717** [comment]
Nicu, 


I know you already answered this, but I cant find tge email.  How do I see the paths and forks for the German World campaign?




Stephen




Get Outlook for Android







On Thu, May 16, 2019 at 8:36 AM -0500, "Philip799" <notifications@github.com> wrote:














Can you change this long ID to standard login, or some shorten, to cloud save?




In 3.2.2 are added only campaigns with maps?

There are some game mechanics change on 3.2.2? In devblog I cant find this.




More mechanics changes can do a great things with this game.

**Comment by Matimbo** [comment]
Looking forward to the iOS version. Great game so far and know it is getting better.

**Comment by Philip799** [comment]
All problems have not only in newest ver. of the game. I think that is in all older ver. 

1. Why can't embark paratroopers on airfields and deploy on air at beginning of the scenarios? (Im have this units without any other land transports) 
2. why cant deploy units on land and air together at the same hex? 
3. How AI units spoting my units? (i think, only in situations when my units escapes after contact) AI air and land units can spot and attack my units in next turn, without any problems in moments when spoting is impassible. (far away from frontline) . This look like the AI have disabled a fog of war restrictions. 
2. Where can I find game mechanics issues. I mean things, like terrain, battle, bonuses and penatlies, units special

**Comment by MansteinlovesGuns** [comment]
Would you guys want help in editing the english text in the game? I have
noticed errors in the campaign descriptions and the messages that appear at
the start of each map before the first turn

**Comment by barsoom1717** [comment]
I'm game, but havent really noticed the errors in the campaigns I've played.




Stephen




Get Outlook for Android







On Sat, May 25, 2019 at 2:29 PM -0500, "MansteinlovesGuns" <notifications@github.com> wrote:










Would you guys want help in editing the english text in the game? I have


noticed errors in the campaign descriptions and the messages that appear at


the start of each map before the first turn

**Comment by MansteinlovesGuns** [comment]
I'll screenshot errors I see and email them.

**Comment by barsoom1717** [comment]
Cool.




Get Outlook for Android







On Sat, May 25, 2019 at 8:42 PM -0500, "MansteinlovesGuns" <notifications@github.com> wrote:










I'll screenshot errors I see and email them.

**Comment by salexgit** [comment]
Hi all

@ MansteinlovesGuns: Help is always appreciated. Do please let us know which campaign/scenario descriptions have errors and how you would fix or improve them.

@Philip799: Here are some answers to your questions

1. You need air transports to embark paratroopers, number of which is determined by the scenario settings. Most scenarios have 0 air transports unless the scenario designer decided to provide them. And at the moment there is no way to buy air transport units.

2. This is a bug which I also noticed and reported long time ago, but it seems that there are not so many people concerned with it. One way to circumvent around the problem is to move away the land unit before deploying air unit over the same hex. Anyway, this is a bug...

3. The main developer can answer this question better, but I suspect that AI can see all the units. As a very good example, AI can always send air planes to bomb your artillery, bridges, etc. Maybe this AI behavior should be randomized a bit so that it does not look so obvious.

4. Interesting idea. In principle each hex owned by a player can provide visibility for 1-2 hexes around it. I cannot recall such a behavior in PGII, but it can be added to the custom ruleset.

5. Can you please elaborate more on a problem? The game should provide artillery support only for the close combat (and we were discussing some time ago an enhancement to provide it also for the raged attack). So, if the AA unit triggers enemy artillery support while attacking another unit at distance more than 1 hex, this is not right. Do you have a saved game with this problem?

6. At the moment, no. However, there have been quite many requests to allow for selling/disbanding units; and it was also possible in PGII. I hope we will add this functionality soon.

7. Internally, we have been using two separate unit classes, "flak" and "anti-air", as in PGII. However, it has been causing more problems than benefits because you can model a particular unit behavior by just using one "anti-air" unit class. There was no conclusion on how to proceed...    

Regards, Alex
