### ISSUE TITLE
Italian MAK campaign: various issues

### ISSUE THREAD

**Issue by Themaginotlineww2** [nicupavel/openpanzer#225]
On the italian campaign mission crusader the aftermath, I can't find the capture point and the game has gone over the limit. Also the defense missions in general are difficult to win ,but only because of the final objectives being invisible. Having no clue where they are at any point in the mission is just horrible if I want to win the missions. Is there a way that you could display them on the strategic map or maybe put them in a kind of box of escarpments only accesable by a reinforcement at the end of the unit like in the russian campaign? It's probably just me but I seem to always get defeated by the invisible objectives and not the enemies themselves. This takes the fun away from what could be a fun kind of missions. 
EDIT: I passed the crusader mission because of an accident but am now having a very similar problem with the battle of Gazala

**Comment by salexgit** [comment]
Hi

Thanks a lot for feedback...
We ported this Italian campaign upon a number of requests from other people, whereupon our goal was to make it available for the gaming community as soon as possible. We fixed the most obvious issues, but we did not have enough time to test thoroughly all the scenarios. And since the whole campaign was not designed by us, it is not always clear for us either what was the logic and reasoning behind building a scenario in a particular way. 
In general, PGII did not have a proper concept of the defensive scenario, so in most cases it is modeled through hidden victory hexes forcing you to hold your lines for X turns. And as you said, it could be indeed annoying especially when the scenario is not balanced properly: you defeat all the enemy units before X turns but the scenario does not end.
Good news is that we can always introduce some changes. We will take a closer look at those scenarios.

Regards, Alex

**Comment by MansteinlovesGuns** [comment]
Same issues for me with liebstandarte campaign.  Look for the reinforcement and if it says go to roadblock hex. Send them to the hex that gives a green message. If that makes sense.  Put on th3 hexes whe n you get to that point.

**Comment by Themaginotlineww2** [comment]
I have encountered a new(ish) issue and instead of making a new thread I will add on to this one. The issue is related to #199 but with allied units. It seems that in the beta if I buy units from another country the next level they will turn into flak2s. I have lost dozens of units to this glitch in The campaigns: American world campaign, the italian campaign, German world campaign and british world campaign. The units lost are not limited to a certain class of units and are ALWAYS gone in the next mission. The switch form the bought unit to flak causes the stats to revert to a flak's. Another user said that was due to a failure of an equipment file. Keep in mind this only happens once the country the unit was bought from is not available in the next level I play in. In narvik there was a exception, starting units from Norway spawned in a flaks.

**Comment by salexgit** [comment]
Hi

Thanks for reporting this. This problem has been known for us and we have been thinking how to solve it. At the moment, we are captives of our own optimisations because we try to load only those equipment files, countries of which are indicated explicitly in the scenario file. However, if you buy a unit from the allied country, there is no guarantee that the next scenario will have the corresponding country ID on the country list; and if not, you will see Flaks. 
Maybe we should simply prohibit buying units from other (allied) countries as a temporary solution.

Regards, Alex

**Comment by nicupavel** [comment]
Yes, this is what I'm aiming to do in the next release. Buying core units from other countries will not be allowed in campaign mode.

**Comment by Themaginotlineww2** [comment]
Is It possible to just keep the countries available throughout the campaign to allow for the use of those units?

**Comment by salexgit** [comment]
Hi

As I explained earlier, current implementation loads equipment files based on the list of countries provided in the scenario file, not based on the list of units and countries they belong to. 

I contemplated with the main developer a solution, whereupon game engine would account for both: a) the list of countries in the scenario file description, and b) list of countries which actual units in the saved game belong to. I am of course not in a position to say whether case b) is easy to implement. It should not be that complex in principle, but since I do not have an access to source code, I cannot really say.

**Comment by jonh64** [comment]
I have an issue with the Italian campaign in 3.2.2. On the 2nd turn of ‘onto mersa’ scenario, a British battleship turns up in the middle of the desert.

**Comment by salexgit** [comment]
Hi

The battleship in the middle of the desert has been fixed, it will be in the next release.

**Comment by MansteinlovesGuns** [comment]
I noticed an issue with the British campaign:

Anti tank unit 43 mgg unit doesn't have the ability to attack, it can move
and transport but has no golden circle to indicate it hasnt fired at
beginning of turn.

Also Big red one campaign:

I played this on the previous version, not the beta.

American 43 combat engineer infantry unti has no movement by foot. Im not
sure if this has been fixed to be 2 hex spaces it should be.

**Comment by salexgit** [comment]
Hi

@MansteinlovesGuns: If possible, please do not mix issues by using an existing discussion thread to report new problems. It results in a complete mess and does not allow us to track issues.

Regarding  "43 combat engineers", the problem was noted in #212 and is already fixed in the online beta. Anyway, thanks for reporting :) 
As for "43 mgg", do please consider opening a new issue and upload the saved game so that we can check it easily.

Regards, Alex

**Comment by jonh64** [comment]
I now have another issue in the Italian campaign on 3.2.2 ipad.  in the bardia defensive scenario i can't find the victory hex which means i am unlikely to even win the scenario at all.  any clues as to its whereabouts please?

**Comment by salexgit** [comment]
Hi

I did not play that scenario, but it seems that this is a defensive scenario which you are not supposed to "win" but rather to hold on to each defensive position. However, the scenario description mentions exact coordinates of hidden victory hexes, so may try them. 
Let me know if you still have problems.

Regards, Alex

**Comment by jonh64** [comment]
thanks for the reply. i had noticed on the scenario description that there
is a hidden VH "42,8" yet the hexes on the map only go up to "38,1" so
can't see how to capture/hold it.

**Comment by salexgit** [comment]
Hi

Ok, so the scenario description is wrong. I will check the scenario file and will let you know where those hidden hexes are; and we will also consider updating the scenario description.

Regards, Alex

**Comment by salexgit** [comment]
Hi

@ jonh64: The hidden victory hex is at (8,40). Well, you can win the scenario just in one turn by moving one of your units into that location. 
It seems that the scenario designer logic was as follows: you hold your positions for 28 turns; then at turn 28 reinforcement unit appears in (7,41); you move your unit into the hidden victory hex and escape. However, these are just my speculations...

Regards, Alex

**Comment by jonh64** [comment]
Thank you Alex.

**Comment by jonh64** [comment]
I have encountered another issue in the Italian big campaign (Ipad 3.2.2).  In the 'Crusader' scenario at the start there is one objective to capture, but there are no visible capture hexes.  after a couple of turns this number rises to 2 objectives.  Any idea where these hexes are please?  My Italian forces have been searching for a while now to no avail.

**Comment by salexgit** [comment]
Hi

@jonh64: Can you please indicate which scenario you are referring to, "Operation Crusader" or "Crusader the aftermath"?

**Comment by jonh64** [comment]
operation crusader

**Comment by salexgit** [comment]
Hi

So, the hidden victory hexes are: (20,14), (18,19), (19,22), (34,41), (35,40). All of them are initially owned by "axis" forces except (35,40) owned by "allied", and this is "the remaining objective 1" that you can in the beginning of the game. However, as allied forces start moving, they take other hidden hexes owned by "axis" and thus you see the number of remaining objectives increasing. I suspect that there was some logic behind designing the scenario in such a peculiar way, but the scenario description does not provide the clear answer.

Regards, Alex

**Comment by jonh64** [comment]
Thank you

**Comment by jonh64** [comment]
> EDIT: I passed the crusader mission because of an accident but am now having a very similar problem with the battle of Gazala

How did you complete the mission please? I am experiencing the same problem in this scenario.

**Comment by salexgit** [comment]
Hi

@jonh64: Which scenario do you have a problem with?

**Comment by jonh64** [comment]
> Hi
> 
> @jonh64: Which scenario do you have a problem with?

Unfortunately all of the Italian ones at moment. I too managed to stumble across the hidden hex in crusader aftermath scenario. now have taken all victory hexes in Battle of Gazala scenario, the description still says 4 objectives remaining.

**Comment by salexgit** [comment]
Hi

@jonh64: I see, it seems that quite many scenarios in this campaign have to be revised. We will try to contact the campaign designer to get more clarifications on why there are so many hidden hexes even for those scenarios that do not look like defensive ones. 

Regards, Alex
