### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by nicupavel** [nicupavel/openpanzer#227]
_- (done) Integrate campaign fixes/changes_

_- (done) Disband core units and get prestige back_

_- (done) Add [keyboard shortcuts](https://github.com/nicupavel/openpanzer/wiki/Keyboard-Shortcuts)_
 
_- (done) Deny buying units from other countries in campaign mode_ 

_- (done) Fix Turns per day issue_

_- (done) Tooltips for Objectives, No Ammo, No Fuel over units/hexes_

_- (done) Fix unit types that can be air transported_ 

_- (done) - Allow scenario victory by destroying all units_

_- (done) Build separate apps for Android to include all campaigns

_- (done) Build separate apps for iOS to include all campaigns

_- (done) Save/Load issue on Android.

_- (done) Update Android/iOS Builds

**Comment by salexgit** [comment]
Hi Nicu

Here is a list of further enhancements, which have been discussed in different discussion threads. Most of them require noticeable development efforts, so I tried to organize them in the order of increased complexity.

- Turns per day. As mentioned in #197, even though each scenario has a special parameter indicating how many turns should pass before a new calendar day starts, it is not accounted for. In other words, at the moment every turn triggers a new calendar day.

- Disband/downgrade units. This enhancement has been asked by quite many people, and in fact, is part of the PGII functionality. And though unit downgrading might require more efforts, it should be relatively simple to add a new "disband" button so that we can sell the unit. To make it simple, the amount of received money can be calculated by the same formula which we use now while upgrading units.

- Transport options during upgrade (and related enhancements). As reported in #185, while upgrading a particular unit the game does not enforce you to upgrade the transportation unit, if so required. An idea expressed in #186 is even a more advanced solution that allows to attach/detach transport units.

- Basic and current unit strength. As reported in #193, at the moment the game only supports current unit strength, while SCN files define both basic and current unit strength. The use case is somewhat limited, but it might be useful to model core units of reduced size, e.g. just 2 companies instead of the whole battalion. Similarly, it would allow for buying units of reduced size, e.g. 5 instead of 10. 

- Air-borne and air-transportable units. According to the PGII game model, there are units type, such as paratroopers, that can be deployed to any hex. And on the contrary to it, there are some units, such as light infantry and guns, that can be transported over air but can loaded/unloaded only at airfields. Our game follows somewhat simplified model, in which we do not account for those differences allowing any infantry unit to be transported over air and be paradropped at any hex. As the outcome, some scenarios are logically broken if played with OpenPanzer. There is "Green devils" campaign which is effectively not playable at all with the current version of the game. 

- Flak and anti-air units. PGII has two different unit classes, Flak and anti-air, with somewhat different rules and behavior for each of them; however, those differences are really questionable. For instance, OpenGeneral game deprecated Flak unit class completely and model all the units as anti-air with the corresponding unit attributes. I would suggest following the same principle. We can model all Flak units as anti-air class (and in fact some Flak units are already modeled as anti-air). 

- Profiles/rule sets. Even though we try to follow game model as defined in PGII, there are ideas and proposal to experiment with slightly different rules. As an example, artillery support during the ranged attack, ranged anti-tank attack only during LOS, etc. Instead of hard-coding all these details in the game and arguing which model we should follow, we can just introduce support for "PGII default", "OpenGeneral default", and "custom" profiles so that we can experiment with different game behavior. 

Regards, Alex

**Comment by nicupavel** [comment]
Hi Alex,
Thanks for the nice round up of features !. 1 and 2 might get in the next release.

**Comment by SovietArmyakaRedArmy** [comment]
hey nicu,
i have an idea 
can you separate a land and naval unit deployment so all of ship is now can't deploy in land anymore and make it easier than old unit deployment

**Comment by nicupavel** [comment]
> hey nicu,
> i have an idea
> can you separate a land and naval unit deployment so all of ship is now can't deploy in land anymore and make it easier than old unit deployment

Can you explain in more detail how you see this working ?

**Comment by SovietArmyakaRedArmy** [comment]
to nicu
1.it should have two deployment button(i think you should make a new botton so it not confused with buy button) 
first button have (german)helmet(what ever you want) icon and second have a ship (naval) icon 
2.can only choose the ship in 
naval deployment ( no ship in land deployment)( and naval unit cannot deploy on land anymore [ i mean you have to fix a land battleship problem ((ex. the ship in italy campiagn))]
###extra make a naval poin(money)and player now can buy a ship( i know it hard to do but one day you can do this thing)
by SVAakaRA

**Comment by salexgit** [comment]
Hi

At least I did not fully understand what exactly you propose to introduce. However, it seems that to me that it is already possible with the existing game model:

- Each hex has a special attribute indicating its type, for which we have attributes such as "air field" and "port";
- At the moment "port" hexes are used only to embark units on ships, but you can also consider using those hexes to deploy ships if you have them;
- Nevertheless, keep in mind that at the moment we do not allow buying ships following the same principle as in PG2;

If your concern was about the battleship unit in the Italy campaign, then it is just a wrong unit type which is already fixed.

Regards, Alex

Regards, Alex

**Comment by Philip799** [comment]
is there a chance, to implement all mechanical options from open general on PC, to Android platform? I think some efiles, special ability of units and lots of other maps and campaigns. The newest patch of Open General on PC looks like new game (v3.2.9 of Panzer M its great, but still have many bugs and original abilities of units). This game has a great chance to be a greatest strategy on Android. It's only one other game some similar who I like to play: "Panzer Campaigns"

**Comment by Philip799** [comment]
is there a chance, to implement all options from open general on Android platform? I think some efiles, special ability of units and lots of other maps and campaigns.

**Comment by salexgit** [comment]
Hi

@Philip799: I am not the main developer of the game so I am not the best person to discourse about features that will or shall be implemented, but I will anyway try to answer your question as I have been also pondering a lot about both Open General and Panzer Marshall. Open General has been developed as the PC game focusing on the Windows platform as the main target. You can play it in Linux with the wine emulator, but mobile platforms are out of question as the game was not designed like that in the first place.  On the contrary to it, Panzer Marshal has been designed as a multi-platform application, which however creates other challenges. So, these games pursue somewhat different goals. It is possible to develop Open General running on different platforms, but the amount of work and efforts will be comparable to a proper commercial project. Maybe in X years both projects will be merged leveraging Open General core functionality and features with Panzer Marshal multi-platform UI. Meanwhile, new features are being added to Panzer Marshal, but I doubt we can compete with Open General and this never has been the goal as far as I can see.

Regards, Alex

**Comment by Philip799** [comment]
On open panzer forum I saw some like final compilation, with all features, I think, with features chosen by players, maybe this is the point to create mobile game with all features from PC. If it's true, maybe there is a chance to create project exactly like on PC. Now I'm playing on Panzer M. on mobile and open P. on PC.  :)
