### ISSUE TITLE
Difficulty of Tactical and Operational Difficulty

### ISSUE THREAD

**Issue by PMARC14** [nicupavel/openpanzer#233]
While I really appreciate the new difficulty settings for campaigns, the amounts of prestige given in the difficulty settings is far too much to use. I have had barely made it to mission 4 on the soviet campaign on Tactical difficulty before I was inundated with prestige and nothing to use it on without the number of units turning into a complete slog to move around. The current 10% starting prestige each turn is far too much for the medium difficulty and I am wondering if it is possible to change this additional prestige to be added rather than by turn, but by mission at a different percent if necessary. This would add more to the difficulty of the medium setting and make more sense for the play style of the game I feel.

**Comment by Lutarp** [comment]
This may be just an issue with just the Soviet (and one of the US campaigns) due to the high starting prestige, so another possibility is giving the campaign designers the ability to adjust the difficulty on a per campaign setting, but still a change from receiving prestige from turn based to mission based, or possibly giving more prestige for the objectives/sub-objectives for different difficulty settings would be better ways to make the game easier while also still incentivizing players to play efficiently and strategically.

**Comment by salexgit** [comment]
Hi

Thanks for your comments.

Most campaigns are coming from PGII, and most campaigns are initially designed so that some of them are more challenging and some of them are easier. As far as I remember, there was no concept of the difficulty level in PGII. It means that different difficulty levels in OpenPanzer may lead to somewhat unpredictable results: some campaigns may become even more challenging and some might become very easy.   

There is a way to provide prestige per turn (in addition to per mission), but most campaign/scenario designers do not use this option because it requires too much work and testing efforts to ensure that you do not break the game balance. What I understood is that per turn prestige is used mostly to reinforce and resupply purposes. Otherwise, if the whole prestige is distributed evenly between the turns, you will get less prestige for e.g. a brilliant victory. 

Nevertheless, if you have a specific proposal for a specific scenario, we will be more than happy to take a closer look and readjust if needed.

Regards, Alex
