### ISSUE TITLE
Free French Forces Campaign First Impression

### ISSUE THREAD

**Issue by PanzerWolf** [nicupavel/openpanzer#238]
Feedback FFL Campaign

First of all, thank you for this game, it is awesome! When it’s finished you could do a Steel Panthers Port too ;)

I really enjoy the British Campaign and the LSSAH campaign. The following is my feedback about the FFI campaign. All this is strictly my personal opinion of course.

Scenarios:

Overal feel that the campaign is too short
One scenario is 1941, the next is 1942 and the one after is 1943 so to speak.

It should actually start in Norway with the 13DBLE that formed the core of the 1 FFL Division

Lots of battles are missing: Norway, Gabon, Keren, Tobruk, …

Maps: 

Overal the maps are ok
Except for the fact that all **city names are missing** this should certainly be fixed.

Units:

Lots of units are missing and the ones you can choose from **do not evolve properly** over time.

Also there’s **something wrong with transport options**. You should be able to choose trucks, Bren carriers en M3/M5 halftracks, but the only thing I can choose for Legion troops and many others are bikes. Which is not very historical. (This is also the case for the Sissi troops in the Finnish campaign)

If you can choose the option to buy FFI 1941 Infantry, you should also be able to buy FFI 1942 and 1943/44, instead I can choose Infantry Mécanisée on bikes? And Mechanised Infantry in halftracks. 

In my opinion the entire range of troops should be revised.  I remember the options you had in the British Campaign (Mareth) and the French options were better then.

Proposed order of battle:

1940 Norway: 2 units of Legion 37 (or 40), 1 unit Chasseurs Alpins, 1 unit Fusiliers Marins, 1 artillery, 1 tank, 1 sappeurs

November 1940 Gabon: as above, plus 3 units of Tirailleurs Africains

1941: Battle of Keren: as above, plus 1 unit of Tirailleurs Pacifique

1942: Free French Forces Of The Western Desert: as above, plus 1 Spahi Cavalry Unit and 1 tank unit constituting the FF Flying Column

1943: Chasseurs Afrique Tank Destroyers, all troops motorized 

1944: mechanized

1945: Vosges, Colmar Pocket, Battle of Authion, Tende, La Brigue, end.

I will add more feedback later, when I have replayed it a few times.

Cheers!

**Comment by salexgit** [comment]
Hi PanzerWolf

Thanks a lot for detailed feedback, it is not common to receive well structured comments. I will try to answer some of them.

MAPS: Maps are not designed by us but are coming from the PG2 community, so we just leverage what the PG2 community provides. You might be interested to explore more the following site: http://mapfinder.gilestiel.eu/.
City names usually come with the corresponding map, but if needed we can add easily missing  names.

SCENARIOS: Thanks one more time for the proposed order of battle, appreciated. Good news is that we can add new scenarios, bad news is that this project has very limited resources to design new scenarios from scratch. What I sometimes do is that I try to find a similar scenario from another campaign (e.g. you can search for Italian and German campaigns), and then use it as a starting point for a desired scenario. You can also use the link I posted above to check whether a particular map exists, because if it does, then it means that there must be a scenario. 
=> If it is Ok for you, I can add a page to Wiki where we can capture all your suggestions for this particular campaign formulating a "roadmap" of potential changes.

EQUIPMENT: It is indeed weird that the only thing that you can choose for Legion troops is bikes, it is a bug in the equipment file (which by the way originally also comes from the PG2 community). We have been constantly adding minor fixes to the equipment file, so the transport options should be fixed easily.  
=> If you let us know which units should be fixed and/or which transport options should be added, I can introduce the corresponding changes, which we can push asap to the online beta version. 

Regards, Alex

**Comment by PanzerWolf** [comment]
Hi Alex,

Ok, I will check the maps through the link.

I think the city names are needed, it provides a sense of direction and historical feel.

Please do add the roadmap on the Wiki page.

I will add a list later of proposed transport per unit per year.

Cheers,
Rolf
