### ISSUE TITLE
Enemy spamming cheap units

### ISSUE THREAD

**Issue by jackomago61** [nicupavel/openpanzer#240]
I tried to play the soviet campaign and couldn't complete the first mission cuz the AI started to spam cheap units when it started to lose. I tried again this time on operational difficulty. In the end i destroyed 52 enemy units but i couldn't reach the second objective. I already faced this issue several times but never failed to complete a mission because of it and i wanted to know if that could be a feature to increase difficulty. Thanks!

**Comment by salexgit** [comment]
Hi

I suppose this issue is same as #232. 
I suspect that this is a new AI behaviour that tries to exploit available prestige, maybe @nicupavel can provide more insight on it. I have a feeling that the latest AI version just tries to units as long as it has prestige, but we did not account for the fact that some scenarios could have too much prestige available for the computer player because this is not how PG2 AI worked.

Regards, Alex

**Comment by salexgit** [comment]
This issue will be closed because the same issue #232 is now "fixed-testing".
