### ISSUE TITLE
Unit Move Method Issues + a miscellaneous question

### ISSUE THREAD

**Issue by ImperialCheese** [nicupavel/openpanzer#246]
While looking through the German infantry options, I noticed that the Kavallerie and 39 SS Kavallerie are listed as having the half-tracked movement method. Is this intended? It seems to me that since all other cavalry units are considered all-terrain including later SS Kavallerie units, that it would make more sense for these units to have all-terrain movement as well.

Also, the Italian campaign is listed as being 1940-1945 but as far as I can tell it only goes up to 1943. Is this intended? This isn't a huge deal but I was curious as to the reason.

Edit: oh, and one more thing. The Polish 43 SP Piechota has all-terrain move method while the 44 SP Piechota has leg move method. Given that the 43 and 44 SP Pionerzy also have all-terrain move method, it seems reasonable to me that the 44 SP Piechota should also get this.

**Comment by nicupavel** [comment]
Thanks for bringing this up. I'll change the equipment for as you mention. As for campaign the scenarios end in 1943, maybe the original author intended to continue with other battles on the Italian soil.

**Comment by ImperialCheese** [comment]
Thanks. I've also found that the British 40 Camel and 43 Camel have the tracked move method, and I'm not sure if this is intended or not. Are these intended to be different from other cavalry units or should these have all-terrain movement too?

**Comment by salexgit** [comment]
Hi

If PanzerGeneral follows the same model as PGII, then difference between "all terrain" and "half tracked" is marginal. "All terrain" movement type has benefit only in swaps and streams. However, in snowy weather a half-tracked unit will move a bit faster in swaps (apparently assuming that swap is frozen), while an "all terrain" unit will move at the same speed regardless of the fact whether conditions are fair or snowy.
Nevertheless, I tend to agree that it might be more logical to change all the cavalry units into "all terrain" movement type. Last but not least, PanzerGeneral does not support custom movement sounds, but rather uses the same sound file for a particular movement type. So, a moving cavalry unit with "half tracked" movement type will sound as if it were a tank :)

@nicupavel: Will you do the corresponding polishing work or will you prefer me to take care of it? 

Regards, Alex

**Comment by nicupavel** [comment]
If you have time feel free to do it, I'm working on supporting multiple equipment files so we can port the other campaigns which are based on other equipment files than adlerkorps

**Comment by salexgit** [comment]
Hi Nicu

Ok, I can take care of it. I assume that the repository has the latest EQP file, and the corresponding modifications can be applied straight to it. I can review cavalry units in all the nations to ensure that "all terrain" movement type is used everywhere.

Regards, Alex

**Comment by salexgit** [comment]
Hi again

I revised all the cavalry units for all the countries. So in most cases they indeed have "all-terrain" movement type and it is mostly Germany, for which (apparently by mistake) several cavalry units have "half-tracked" movement type. 

@nicupavel: Should I just commit the EQP file to the master branch?

**Comment by nicupavel** [comment]
Thanks Alex, yes master branch is ok.

**Comment by salexgit** [comment]
Hi

While trying to commit to the master, I got the following error messages. I am not sure whether it is because the repository is full or because I do not have rights to commit to the master branch.

Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 456 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Repository is over the size limit (2 GB) and will not accept further additions.
remote: 
remote: Learn how to reduce your repository size: https://confluence.atlassian.com/x/xgMvEw.To https://bitsalex@bitbucket.org/npavel/pg2-openpanzer.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://bitsalex@bitbucket.org/npavel/pg2-openpanzer.git'

I can just upload EQP file here, if it is a simpler way.

**Comment by nicupavel** [comment]
Looks like it needs some cleanup

**Comment by salexgit** [comment]
Hi Nicu

I committed fixes for the German cavalry units into the new repository. I also checked _all_ the cavalry units of other nations, but they use "all terrain" movement type. So it seems that the problem was only with the aforementioned German units.

As an additional piece of information, there are camel units belonging to France and UK, that use "tracked" movement type. I am not sure whether it is intentional or unit, but at least all the camel units use "tracked" type; at least it is consistent. Thus I decided not to change it for now.

Regards, Alex
