### ISSUE TITLE
German Das Reich campaign: Smolensk scenario

### ISSUE THREAD

**Issue by samrommel** [nicupavel/openpanzer#250]
Hello I'm having issues with the days Reich campaign, after I capture the last objective on the Smolensk crossing the dnepr level the game freezers, and it won't go to the next level.
I've tried restarting and then complete the level again, still with same issue.
Any help would be appreciated

Thank you

**Comment by salexgit** [comment]
Hi

I remember seeing the same issue at least while playing on mobile devices; but I ever encountered it on a desktop. If you play on a mobile device, then one way to circumvent around the problem would be to open the saved game on a desktop computer, transit to the next scenario, and then resume the game on a mobile device.
You can also post the ID of the saved game here _before_ you capture the last victory hex so that we can try to reproduce the problem.

**Comment by samrommel** [comment]
Hello, I've been playing the game on an Android device (Moto e), there's no
error message for the freeze.

Many thanks

**Comment by salexgit** [comment]
Hi

If you experience the same problem I faced several times before, then there is no error message; the game just freezes. So what we ideally would like to have is the ID of the saved game _before_ you capture the last victory hex (at which point the actual problem emerges).

**Comment by 1stLeonidas** [comment]
Hi I have the same problem. Playing on laptop Pc. Installed game. 

Great game btw. 

Id: ea0318e92a549c3c70f1d2ab1fc1f337

**Comment by 1stLeonidas** [comment]
I have the same issue when testing the save on my Ipad.

**Comment by salexgit** [comment]
Hi all

Thanks a lot for your feedback!
@1stLeonidas: I loaded your saved game through the online game version, it works for me. Can you please try (and confirm) that it works in the online version but does not work on the locally installed game?

**Comment by 1stLeonidas** [comment]
Hi! It works with the online version.

**Comment by salexgit** [comment]
Hi 

@1stLeonidas: Thanks a lot for checking. It is a bit weird that it works for online version but not for local one, usually we have some issues with the online version due to firewalls and ad-blockers. I tried saved game with the local version, on MacOS and Linux, and it still works for me. Can you please indicate which operating system you use?

**Comment by 1stLeonidas** [comment]
Hi!

Both have Win10 and ios on the Ipad.

**Comment by salexgit** [comment]
Hi

I loaded saved game on Android (Samsung Note8) and iOS (iPhone 11), both works fine for me. So I suspect that this some weird combination of the run time environment and something in the game data.
I will add a "bug" tag for this issue so that the main developer can try to reproduce the problem on e.g. Windows 10. If not, then it will be somewhat difficult to fix it.

**Comment by 1stLeonidas** [comment]
Ok, thanks. I´ll get by by switching from online back to desktop.

**Comment by salexgit** [comment]
@nicupavel: Hi Nicu. It seems that there is an issue reported by several users, which occurs at several platforms/environments, saved game for which is here: ea0318e92a549c3c70f1d2ab1fc1f337. I also attached the corresponding saved game file.

[(Campaign) Smolensk-Crossing the Dnepr Turn 9 Thu Jan 16 2020 10_58_19.json.zip](https://github.com/nicupavel/openpanzer/files/4070825/Campaign.Smolensk-Crossing.the.Dnepr.Turn.9.Thu.Jan.16.2020.10_58_19.json.zip)

Just for information, the problem was reported for Android, iPad, and Windows 10. I unfortunately was not able to reproduce the problem on Samsung Note 8, and iPhone 11 also works fine for me.

**Comment by salexgit** [comment]
Hi again

Just for information, similar symptoms for the same scenario were reported earlier here #170. I am not sure though whether the root cause is the same.

**Comment by layssi** [comment]
Sam's here. On android pixel 4.
