### ISSUE TITLE
Unable to reload save game

### ISSUE THREAD

**Issue by 11acav** [nicupavel/openpanzer#257]
I have donated and downloaded Panzer Marshal. Looks great but then I am not able to load any save games at all.

I then tried to play the browser version and encountered the same problem. Given up on this.

I hope you will be able to fix this issue.

**Comment by GManev50** [comment]
Actually You cannot reload only game, saved under new version - 3.2.7. At least that's my case - and I play trough browser. I also noticed files saved under new version are some 200 KB smaller ...

**Comment by nicupavel** [comment]
I had to optimize game save data. It should work with saves from older version, but I can see there are issues. Best advice would be to attach here a save that doesn't load and until I fix it play the previous version until you finish the campaign (http://panzermarshal.com/prev)

**Comment by GManev50** [comment]
Tried sending message - rejected by GitHub messaging subsystem, as follows :
"Hi, Sir !
Thanks for Your response . Enclosed I send You two files - saves on same campaign and same scenario - one on the old version and the later one - on the last . I also send some screenshots :
1. Pic 1 - conditions I use to play on Opera browser
2. Pic 2 - what happens on loading old save. Clearly visible is absence of sub-menu which shows history and winning conditions
3. Pic 3 - what happens on loading new save - quite unsatissfactioning - e.g. start tutorial
Besides there is some strange issue in German world campaign itself - AFTER army successfully wined Windsoor in 1940 it had to conquer England again in 1945. A bit absence of military (and historical) logic, as is the lack of weapons perfection for wining German army in 1946, but not crucial for playing the game :)
What IS CRUCIAL, however - the link You recommend doesen't work at all - see enclosed pic. untitled.jpg
Probably - at least for non Android users, the old version should temporarily be made available again instead of latest one.
Hope You will forgive my long writings - I'm just an old dye hard Panzer General fan and You game captured my admiration since 2018.
Regards
"
In addition system rejected .json files - so I send the two in one .zip 
Let's this will work :)
![Pic 1_2020-03-27_153654_panzermarshal com](https://user-images.githubusercontent.com/62619482/77821804-abcf2800-70f5-11ea-910b-1bd6879cc618.png)
![Pic 2_2020-03-27_153855_panzermarshal com](https://user-images.githubusercontent.com/62619482/77821808-b38ecc80-70f5-11ea-9464-9e03af737cd0.png)
![Pic 3_2020-03-27_154204_panzermarshal com](https://user-images.githubusercontent.com/62619482/77821811-b8538080-70f5-11ea-915a-15491deb23ff.png)
![Untitled](https://user-images.githubusercontent.com/62619482/77821813-b984ad80-70f5-11ea-8acf-b172f6e8397b.jpg)

[(Campaign) Invasion England 1945.zip](https://github.com/nicupavel/openpanzer/files/4397009/Campaign.Invasion.England.1945.zip)

**Comment by CCMM2** [comment]
[Archive.zip](https://github.com/nicupavel/openpanzer/files/4415705/Archive.zip)
Hello Nicu,
As requested, please find attached 2 compressed save games.
Thank you

**Comment by nicupavel** [comment]
Thank you going to take a look.
