### ISSUE TITLE
Range 2 tanks do not retaliate

### ISSUE THREAD

**Issue by Brotrob** [nicupavel/openpanzer#262]
There's a bug with range 2 tanks - they don't retaliate when attacked by other range 2+ enemies, e.g. tanks, ATs etc. As it is now, you can attack and wear down even the highest experience tank unit with low experience range 2 tanks without suffering any losses at all. 

This seems wrong, as the principle of PG is that units have unlimited retaliations when attacked.

**Comment by salexgit** [comment]
Hi

I assume that a tank cannot retaliate if it is attacked by 2+ range unit, e.g. artillery, but are you sure that it does not fire back if it is attacked by another tank? Do you have a saved game illustrating this? Maybe this is a problem with a new version because I clear remember range 2 duels. 

Regards, Alex

**Comment by Brotrob** [comment]
Hi Alex,

Yes, that's true, it does not work in tank vs tank duels. This issue was present before this new version came out, and is also the case now. 

I cannot save any games now anymore, due to the (known) bug, but you can test by playing the Seelow Heights scenario for Germans and sending any range 2 German tank towards the front, and waiting for the Russian turn. You'll then see your tank to be attacked by tanks from range 2, and you won't retaliate.

**Comment by Brotrob** [comment]
Bump - still the same problem
