### ISSUE TITLE
Transvestite brigade?

### ISSUE THREAD

**Issue by campaignbuff** [nicupavel/openpanzer#265]
I replayed the Italian campaign, I don’t recall this...

![A5E18E69-3557-4E6F-BE3D-77B39096D807](https://user-images.githubusercontent.com/45533789/78941109-50b71100-7ab7-11ea-9043-f249c089a09f.jpeg)

Guess this was a joke by the creator... can it be removed?

**Comment by barsoom1717** [comment]
Why remove it.  It's funny.
Stephen
    On Thursday, April 9, 2020, 4:12:05 PM CDT, Edward Smith <notifications@github.com> wrote:  
 
 


I replayed the Italian campaign, I don’t recall this...



Guess this was a joke by the creator... can it be removed?

**Comment by campaignbuff** [comment]
Well because in my striving to get and play a campaign as historical as possible, getting to fight a brigade of trans that have more firepower than a battleship is a bit disappointing.
Especially when everything went just fine for all the damn campaign, to just get this troll at the very end is a bit anticlimactic.

**Comment by barsoom1717** [comment]
Good points.  Didn't realize they had that much combat power.
Stephen
    On Saturday, April 11, 2020, 7:13:03 AM CDT, Edward Smith <notifications@github.com> wrote:  
 
 


Well because in my striving to get and play a campaign as historical as possible, getting to fight a brigade of trans that have more firepower than a battleship is a bit disappointing.
Especially when everything went just fine for all the damn campaign, to just get this troll at the very end is a bit anticlimactic.
