### ISSUE TITLE
Flak thoughts

### ISSUE THREAD

**Issue by Feldmarshalruge** [nicupavel/openpanzer#270]
Why can we not purchase some of the older 1938 flak guns for Germany?  Flakvierling38 or original 37mm flak that can be defensively used.

**Comment by salexgit** [comment]
Hi

A similar issue was already raised before and discussed here #155. 

Long story short, instead of having just one common "AA" unit class (and allowing some units to attack also ground targets), the original PGII game introduced two classes: "AA" and "Flak". We have to live with that legacy design because the equipment file has some units modelled as Flak, and some of them are AA. I do not remember whether PGII game allowed buying Flak units, but OpenPanzer intentionally does not allow it. I had once a discussion with the main developer why it was prohibited, but cannot recall what the reason is. Technically, there should be no problem with showing Flak units in the same pane where other AA units are, as a quick and dirty solution.

In general, Flak units are the mess and the most eloquent example is 8.8 Flak 36. It appears twice on the unit list - as the air-defence unit and anti-tank - with different technical characteristics. So, instead of buying just one Flak unit to attack both ground and air units (as German did), you will resort for buying two different units. So it is not only about enabling Flak units on the purchase window, but also about polishing the equipment file. Anyway, this is an enhancement that definitely should be done, as far as I can see.

Regards, Alex
