### ISSUE TITLE
Buying allies units 

### ISSUE THREAD

**Issue by Feldmarshalruge** [nicupavel/openpanzer#274]
How come we are unable to purchase axis forces on German campaign that are allies?  Would love to play w those too.

**Comment by salexgit** [comment]
Hi

It was possible in earlier releases, but this feature was deprecated in later versions. Here are some explanations why it was removed:

- When you start / load a particular scenario, the game engine loads equipment files that correspond to the countries indicated in the scenario file;
- If you have a unit belonging to a particular country, but this country is not indicated in the scenario file, then you will see a weird glitch as the "missing" unit will be rendered as Flak or something similar;
- So the most common problem was that you start a scenario with e.g. German (main) and Italian (secondary) forces, buy an Italian unit, move to the next scenario which does not have Italian forces. And since the scenario information does not assume presence of Italian forces, the Italian equipment file is not loaded and the unit, which you bought in the previous scenario, will not be rendered properly.

According to the explanations from the main developer, we do not load all the equipment files to save memory, but rather rely upon the country list that the scenario file description has. One potential workaround for the problem was not to rely upon the scenario country list, but rather analyse explicitly countries to which units belong. I do not have a good explanation why it was not implemented that way, maybe it required more efforts, and instead we just abandoned a possibility to buy allies units. 

I hope it explains the background. Nevertheless, I marked it as "enhancement" so that we can revise this issue later.  

Regards, Alex
