### ISSUE TITLE
Propably most annoying problems

### ISSUE THREAD

**Issue by Philip799** [nicupavel/openpanzer#282]
@nicupavel, you doing a great job with panzer Marshal, and I think that is a 
the best strategy game on Android. 
1. Is there a chance to fix problem with AI spotting? I think that AI don't have restriction about fog of war, and spot all units on map.
2. second thing is about defending strategic places. after update, AI still can abandon fortified strategic points, and attack enemy.
3. still have problem with deploying units on the same hexes (air units and ground) 

there is a more things, but this problems I think was before on original PG2.

I,m testing game on www 3.2.8 and changes don't always work.
Ps. when Android applications will be updated?

sry 4 my eng :)

**Comment by Philip799** [comment]
> 1. Is there a chance to fix problem with AI spotting? I think that AI don't have restriction about fog of war, and spot all units on map.
> 2. second thing is about defending strategic places. AI always leaving fortified strategic points, and attack enemy.
> 3. problem with deploying units on the same hexes (air units and ground)
> 
> there is a more things, but this problems I think was before on original PG2.
> 
> sry 4 my eng :)

I,m testing game on www 3.2.8 and changes don't always work.
Ps. when Android applications will be updated

**Comment by salexgit** [comment]
Hi

1. I assume that this is the same issue as raised many times, in particular here #249. I let the main developer to comment on when it will be improved, but I can imagine easily that it is not a straightforward enhancement as you would need to change completely AI logic making it smarter. 

2. I thought it was fixed cause I reported the same problem some time ago to the main developer, and the intention was to fix it. Maybe it was improved but not entirely.

3. Is it the same problem as reported here, #109? The workaround I ended up with was that you deploy first the ground unit, move it away, and then deploy the air unit (or vice versa). As a more generic comment, if I recall correctly, in PG2 you can deploy air units only to the airfield hexes. So, maybe one way to "solve" this problem is to follow the PG2 model of deploying air units.

Regards, Alex

**Comment by Philip799** [comment]
[sorry for my eng, I'm from Poland :) ] 
about this problems:
I'm playing PM allways on android browser. I think the interface problem is on smartfons touch screens. PC ver with the mouse interface working much better.
I think, the Better will be to get more attention with fixing  Android version bugs, beacouse on PC more players just choose the open panzer, witch more options, mechanics etc.
Panzer Marshal is the best turn strategy on Android and propably iOS platforms.
That's I think, the most priority with patching / fixing must be doing on Android platform where is no serious competition.
