### ISSUE TITLE
Can't load from disk on android

### ISSUE THREAD

**Issue by irheavyd69** [nicupavel/openpanzer#291]
I am playing turni g tides that I downloaded from google play store.  I can't load anything from disk once I save it.  Ca. Only continue game

**Comment by Tobias004** [comment]
> I am playing turni g tides that I downloaded from google play store. I can't load anything from disk once I save it. Ca. Only continue game

the same by me!
This issue is reproducable: 
- load from store
- play american campaign
- save every 1st turn on new map to cloud (overwrite) and disc!
- save in game on same map to disc only serveral times on different moves
- load some older saves for each map
when reaching map: dday at round 11 load from disc another savegame with a previous map

when the bug uccures the text "last savegame" for disc on load screen says none.
