### ISSUE TITLE
Add NATO Joint Military Symbology units icons as an alternative 

### ISSUE THREAD

**Issue by mastro35** [nicupavel/openpanzer#292]
It would be great to have also NATO 2d icons as an alternative. 
They would be also more readable for wargame player.

https://en.wikipedia.org/wiki/NATO_Joint_Military_Symbology

**Comment by salexgit** [comment]
Hi

I wanted to post a response to this question, but I never had enough to do that...

So, technically speaking, showing NATO symbols instead of existing icon is doable. The unit database is organised in such a way that each unit information has a "pointer" to the graphic file, so we can replace them with something else. The only problem I see is that NATO symbols were introduced not only to show a particular unit type, but also its "echelon" level, i.e. company, battalion, regiment, division, etc. And there is no concept of the echelon level in OpenPanzer, one unit can be whatever you like - a company or a regiment - and it depends on your preference and the scale of the battle you model. Another potential issue is that if you show all the tanks as e.g. NATO tank symbol, then how would you differentiate between your units if you have e.g. PzII, PzIIIH, PzIIIG, PzIV and PzV tanks? Same problem goes into the artillery units and other unit types. NATO symbols allow having special qualifiers attached to every symbol, but I could not help but wonder whether we will have enough space to render symbols and associated text. 

As a summary, this is a good idea, especially if some day every unit will have an additional parameter telling whether it is a company, battalion, regiment, etc. 

Regards, Alex
