### ISSUE TITLE
Limoges mobility issue

### ISSUE THREAD

**Issue by Cjh1953** [nicupavel/openpanzer#53]
Have tried this scenario twice in DAs Reich Campaign. There is no way to move the German units out of the corner where they enter. All I can do, is to cycle the AI until the scenario is over and move on.

This is the best game of this type I've found. I hope some of the glitches can be sorted. It is worth fixing. I'd be happy to purchase an upgrade if it resolves these issues. 

Thanks for building this great game.

**Comment by lukewarrendc** [comment]
I have this problem to in IOS

**Comment by nicupavel** [comment]
Fixed, will be online soon. Thanks for reporting.

**Comment by Cjh1953** [comment]
Fantastic!

**Comment by lukewarrendc** [comment]
Thanks!  When is the update going live?

**Comment by hahnicity** [comment]
+1 for fixes!

**Comment by nicupavel** [comment]
There is a new version out (2.9.5) at http://openpanzer.net let me know if it fixes this issue. iOS/Android build should come in February 2016.

**Comment by salexgit** [comment]
Hi Nicu

I started to play "March to Limoges" scenario from DasReich campaign and noticed that the issues is still there. When you deploy units, you cannot move them out of the left bottom corner of the map, as the attached screenshot shows.


The root cause for this problem is quite funny. For some reason all the diagonal hexes starting from (34,1) to (38.8) have "escarpment" terrain type so that none of the ground units can escape this corner. Air units can of course be moved when they are deployed. Do you have any idea whether it is a bug of feature? I am not getting the point of allowing to deploy units and trapping them in the corner of the map.

![limoges](https://user-images.githubusercontent.com/22852936/45260237-1e7c9380-b3ea-11e8-87c8-dbfbb239ec06.png)

Assuming that this is not the intended behavior, I can provide the fix for the MAP file so that "escarpment" terrain type is changed to a proper normal terrain type. As an alternative, we can change the SCN file and specify deployment tiles outside that corner area.

Regards, Alex

**Comment by salexgit** [comment]
Hi again

False alarm... Somehow I ended up having old .MAP file, while the latest .MAP file already contains the aforementioned fixes. Sorry for confusion...
